#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 135
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 52
#define ALIAS_COUNT 0
#define TOKEN_COUNT 27
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 2

enum {
  anon_sym_LF = 1,
  anon_sym_if = 2,
  anon_sym_elif = 3,
  anon_sym_else = 4,
  anon_sym_endif = 5,
  sym__DECIMAL_NUMBER = 6,
  anon_sym_0o = 7,
  sym__OCTAL_NUMBER = 8,
  anon_sym_0x = 9,
  sym__HEX_NUMBER = 10,
  sym_escape_sequence = 11,
  anon_sym_SQUOTE = 12,
  aux_sym_string_simple_token1 = 13,
  anon_sym_SQUOTE_SQUOTE_SQUOTE = 14,
  aux_sym_string_multiline_token1 = 15,
  anon_sym_SQUOTE_SQUOTE = 16,
  anon_sym_true = 17,
  anon_sym_false = 18,
  anon_sym_LBRACK = 19,
  anon_sym_COMMA = 20,
  anon_sym_RBRACK = 21,
  anon_sym_LF2 = 22,
  anon_sym_CR_LF = 23,
  anon_sym_LBRACE = 24,
  anon_sym_RBRACE = 25,
  anon_sym_COLON = 26,
  sym_source_file = 27,
  sym_build_definition = 28,
  sym_statement = 29,
  sym_selection_statement = 30,
  sym_condition = 31,
  sym_expression = 32,
  sym_literal = 33,
  sym_integer_literal = 34,
  sym_decimal_literal = 35,
  sym_octal_literal = 36,
  sym_hex_literal = 37,
  sym_string_literal = 38,
  sym_string_simple = 39,
  sym_string_multiline = 40,
  sym_boolean_literal = 41,
  sym_array_literal = 42,
  sym__NEWLINE = 43,
  sym_dictionary_literal = 44,
  sym_key_value_item = 45,
  aux_sym_build_definition_repeat1 = 46,
  aux_sym_selection_statement_repeat1 = 47,
  aux_sym_string_simple_repeat1 = 48,
  aux_sym_string_multiline_repeat1 = 49,
  aux_sym_array_literal_repeat1 = 50,
  aux_sym_dictionary_literal_repeat1 = 51,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_if] = "if",
  [anon_sym_elif] = "elif",
  [anon_sym_else] = "else",
  [anon_sym_endif] = "endif",
  [sym__DECIMAL_NUMBER] = "_DECIMAL_NUMBER",
  [anon_sym_0o] = "0o",
  [sym__OCTAL_NUMBER] = "_OCTAL_NUMBER",
  [anon_sym_0x] = "0x",
  [sym__HEX_NUMBER] = "_HEX_NUMBER",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_simple_token1] = "string_simple_token1",
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = "'''",
  [aux_sym_string_multiline_token1] = "string_multiline_token1",
  [anon_sym_SQUOTE_SQUOTE] = "''",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LF2] = "\n",
  [anon_sym_CR_LF] = "\r\n",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_COLON] = ":",
  [sym_source_file] = "source_file",
  [sym_build_definition] = "build_definition",
  [sym_statement] = "statement",
  [sym_selection_statement] = "selection_statement",
  [sym_condition] = "condition",
  [sym_expression] = "expression",
  [sym_literal] = "literal",
  [sym_integer_literal] = "integer_literal",
  [sym_decimal_literal] = "decimal_literal",
  [sym_octal_literal] = "octal_literal",
  [sym_hex_literal] = "hex_literal",
  [sym_string_literal] = "string_literal",
  [sym_string_simple] = "string_simple",
  [sym_string_multiline] = "string_multiline",
  [sym_boolean_literal] = "boolean_literal",
  [sym_array_literal] = "array_literal",
  [sym__NEWLINE] = "_NEWLINE",
  [sym_dictionary_literal] = "dictionary_literal",
  [sym_key_value_item] = "key_value_item",
  [aux_sym_build_definition_repeat1] = "build_definition_repeat1",
  [aux_sym_selection_statement_repeat1] = "selection_statement_repeat1",
  [aux_sym_string_simple_repeat1] = "string_simple_repeat1",
  [aux_sym_string_multiline_repeat1] = "string_multiline_repeat1",
  [aux_sym_array_literal_repeat1] = "array_literal_repeat1",
  [aux_sym_dictionary_literal_repeat1] = "dictionary_literal_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elif] = anon_sym_elif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_endif] = anon_sym_endif,
  [sym__DECIMAL_NUMBER] = sym__DECIMAL_NUMBER,
  [anon_sym_0o] = anon_sym_0o,
  [sym__OCTAL_NUMBER] = sym__OCTAL_NUMBER,
  [anon_sym_0x] = anon_sym_0x,
  [sym__HEX_NUMBER] = sym__HEX_NUMBER,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_simple_token1] = aux_sym_string_simple_token1,
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = anon_sym_SQUOTE_SQUOTE_SQUOTE,
  [aux_sym_string_multiline_token1] = aux_sym_string_multiline_token1,
  [anon_sym_SQUOTE_SQUOTE] = anon_sym_SQUOTE_SQUOTE,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LF2] = anon_sym_LF,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_source_file] = sym_source_file,
  [sym_build_definition] = sym_build_definition,
  [sym_statement] = sym_statement,
  [sym_selection_statement] = sym_selection_statement,
  [sym_condition] = sym_condition,
  [sym_expression] = sym_expression,
  [sym_literal] = sym_literal,
  [sym_integer_literal] = sym_integer_literal,
  [sym_decimal_literal] = sym_decimal_literal,
  [sym_octal_literal] = sym_octal_literal,
  [sym_hex_literal] = sym_hex_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_string_simple] = sym_string_simple,
  [sym_string_multiline] = sym_string_multiline,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_array_literal] = sym_array_literal,
  [sym__NEWLINE] = sym__NEWLINE,
  [sym_dictionary_literal] = sym_dictionary_literal,
  [sym_key_value_item] = sym_key_value_item,
  [aux_sym_build_definition_repeat1] = aux_sym_build_definition_repeat1,
  [aux_sym_selection_statement_repeat1] = aux_sym_selection_statement_repeat1,
  [aux_sym_string_simple_repeat1] = aux_sym_string_simple_repeat1,
  [aux_sym_string_multiline_repeat1] = aux_sym_string_multiline_repeat1,
  [aux_sym_array_literal_repeat1] = aux_sym_array_literal_repeat1,
  [aux_sym_dictionary_literal_repeat1] = aux_sym_dictionary_literal_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endif] = {
    .visible = true,
    .named = false,
  },
  [sym__DECIMAL_NUMBER] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_0o] = {
    .visible = true,
    .named = false,
  },
  [sym__OCTAL_NUMBER] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_0x] = {
    .visible = true,
    .named = false,
  },
  [sym__HEX_NUMBER] = {
    .visible = false,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_simple_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_multiline_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_build_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_selection_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_decimal_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_octal_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_simple] = {
    .visible = true,
    .named = true,
  },
  [sym_string_multiline] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_array_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__NEWLINE] = {
    .visible = false,
    .named = true,
  },
  [sym_dictionary_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_key_value_item] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_build_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_selection_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_simple_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_multiline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dictionary_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_key = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(35);
      if (lookahead == '\'') ADVANCE(57);
      if (lookahead == ',') ADVANCE(68);
      if (lookahead == '0') ADVANCE(45);
      if (lookahead == ':') ADVANCE(73);
      if (lookahead == '[') ADVANCE(67);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == ']') ADVANCE(69);
      if (lookahead == 'e') ADVANCE(50);
      if (lookahead == 'f') ADVANCE(49);
      if (lookahead == 'i') ADVANCE(13);
      if (lookahead == 't') ADVANCE(21);
      if (lookahead == '{') ADVANCE(71);
      if (lookahead == '}') ADVANCE(72);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(42);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '7')) ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'd')) ADVANCE(52);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(6)
      if (lookahead == '\'') ADVANCE(56);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0) ADVANCE(60);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(70);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(36);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(57);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0) ADVANCE(63);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(61);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(56);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      END_STATE();
    case 7:
      if (lookahead == 'U') ADVANCE(33);
      if (lookahead == 'u') ADVANCE(29);
      if (lookahead == 'x') ADVANCE(27);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == 'd') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(39);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(65);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 13:
      if (lookahead == 'f') ADVANCE(37);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(38);
      END_STATE();
    case 15:
      if (lookahead == 'f') ADVANCE(40);
      END_STATE();
    case 16:
      if (lookahead == 'i') ADVANCE(14);
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 17:
      if (lookahead == 'i') ADVANCE(15);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(16);
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 19:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(44);
      if (lookahead == 'x') ADVANCE(48);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(23);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(12);
      END_STATE();
    case 23:
      if (lookahead == 'u') ADVANCE(11);
      END_STATE();
    case 24:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(24)
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(47);
      END_STATE();
    case 25:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(25)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 26:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(53);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(26);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(27);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(28);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(29);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(30);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 34:
      if (eof) ADVANCE(35);
      if (lookahead == '\'') ADVANCE(58);
      if (lookahead == '0') ADVANCE(20);
      if (lookahead == '[') ADVANCE(67);
      if (lookahead == ']') ADVANCE(69);
      if (lookahead == 'e') ADVANCE(18);
      if (lookahead == 'f') ADVANCE(8);
      if (lookahead == 'i') ADVANCE(13);
      if (lookahead == 't') ADVANCE(21);
      if (lookahead == '{') ADVANCE(71);
      if (lookahead == '}') ADVANCE(72);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(34)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_elif);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_endif);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym__DECIMAL_NUMBER);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(41);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym__DECIMAL_NUMBER);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(42);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym__DECIMAL_NUMBER);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_0o);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym__OCTAL_NUMBER);
      if (lookahead == 'o') ADVANCE(44);
      if (lookahead == 'x') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(46);
      if (lookahead == '8' ||
          lookahead == '9' ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym__OCTAL_NUMBER);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(46);
      if (lookahead == '8' ||
          lookahead == '9' ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym__OCTAL_NUMBER);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_0x);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__HEX_NUMBER);
      if (lookahead == 'a') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('b' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__HEX_NUMBER);
      if (lookahead == 'l') ADVANCE(16);
      if (lookahead == 'n') ADVANCE(9);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__HEX_NUMBER);
      if (lookahead == 'l') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__HEX_NUMBER);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '\'') ADVANCE(64);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '\'') ADVANCE(5);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_string_simple_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_string_simple_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_SQUOTE_SQUOTE_SQUOTE);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_string_multiline_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_string_multiline_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_SQUOTE_SQUOTE);
      if (lookahead == '\'') ADVANCE(61);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_LF2);
      if (lookahead == '\n') ADVANCE(70);
      if (lookahead == '\r') ADVANCE(2);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 34},
  [2] = {.lex_state = 34},
  [3] = {.lex_state = 34},
  [4] = {.lex_state = 34},
  [5] = {.lex_state = 34},
  [6] = {.lex_state = 34},
  [7] = {.lex_state = 34},
  [8] = {.lex_state = 34},
  [9] = {.lex_state = 34},
  [10] = {.lex_state = 34},
  [11] = {.lex_state = 34},
  [12] = {.lex_state = 34},
  [13] = {.lex_state = 34},
  [14] = {.lex_state = 34},
  [15] = {.lex_state = 34},
  [16] = {.lex_state = 34},
  [17] = {.lex_state = 34},
  [18] = {.lex_state = 34},
  [19] = {.lex_state = 34},
  [20] = {.lex_state = 34},
  [21] = {.lex_state = 34},
  [22] = {.lex_state = 34},
  [23] = {.lex_state = 34},
  [24] = {.lex_state = 34},
  [25] = {.lex_state = 34},
  [26] = {.lex_state = 34},
  [27] = {.lex_state = 34},
  [28] = {.lex_state = 4},
  [29] = {.lex_state = 4},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 4},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 34},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 34},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 34},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 2},
  [81] = {.lex_state = 2},
  [82] = {.lex_state = 2},
  [83] = {.lex_state = 2},
  [84] = {.lex_state = 2},
  [85] = {.lex_state = 2},
  [86] = {.lex_state = 2},
  [87] = {.lex_state = 2},
  [88] = {.lex_state = 2},
  [89] = {.lex_state = 2},
  [90] = {.lex_state = 2},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 2},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 3},
  [102] = {.lex_state = 3},
  [103] = {.lex_state = 3},
  [104] = {.lex_state = 3},
  [105] = {.lex_state = 3},
  [106] = {.lex_state = 3},
  [107] = {.lex_state = 3},
  [108] = {.lex_state = 3},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 24},
  [111] = {.lex_state = 25},
  [112] = {.lex_state = 3},
  [113] = {.lex_state = 3},
  [114] = {.lex_state = 3},
  [115] = {.lex_state = 3},
  [116] = {.lex_state = 3},
  [117] = {.lex_state = 3},
  [118] = {.lex_state = 3},
  [119] = {.lex_state = 3},
  [120] = {.lex_state = 3},
  [121] = {.lex_state = 3},
  [122] = {.lex_state = 3},
  [123] = {.lex_state = 24},
  [124] = {.lex_state = 25},
  [125] = {.lex_state = 3},
  [126] = {.lex_state = 3},
  [127] = {.lex_state = 3},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 3},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 24},
  [132] = {.lex_state = 25},
  [133] = {.lex_state = 3},
  [134] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_endif] = ACTIONS(1),
    [sym__DECIMAL_NUMBER] = ACTIONS(1),
    [anon_sym_0o] = ACTIONS(1),
    [sym__OCTAL_NUMBER] = ACTIONS(1),
    [anon_sym_0x] = ACTIONS(1),
    [sym__HEX_NUMBER] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE_SQUOTE] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(130),
    [sym_build_definition] = STATE(128),
    [sym_statement] = STATE(11),
    [sym_selection_statement] = STATE(127),
    [sym_expression] = STATE(127),
    [sym_literal] = STATE(126),
    [sym_integer_literal] = STATE(102),
    [sym_decimal_literal] = STATE(115),
    [sym_octal_literal] = STATE(115),
    [sym_hex_literal] = STATE(115),
    [sym_string_literal] = STATE(102),
    [sym_string_simple] = STATE(114),
    [sym_string_multiline] = STATE(114),
    [sym_boolean_literal] = STATE(102),
    [sym_array_literal] = STATE(102),
    [sym_dictionary_literal] = STATE(102),
    [aux_sym_build_definition_repeat1] = STATE(11),
    [anon_sym_if] = ACTIONS(3),
    [sym__DECIMAL_NUMBER] = ACTIONS(5),
    [anon_sym_0o] = ACTIONS(7),
    [anon_sym_0x] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
  },
  [2] = {
    [sym_statement] = STATE(3),
    [sym_selection_statement] = STATE(116),
    [sym_expression] = STATE(116),
    [sym_literal] = STATE(126),
    [sym_integer_literal] = STATE(102),
    [sym_decimal_literal] = STATE(115),
    [sym_octal_literal] = STATE(115),
    [sym_hex_literal] = STATE(115),
    [sym_string_literal] = STATE(102),
    [sym_string_simple] = STATE(114),
    [sym_string_multiline] = STATE(114),
    [sym_boolean_literal] = STATE(102),
    [sym_array_literal] = STATE(102),
    [sym_dictionary_literal] = STATE(102),
    [aux_sym_build_definition_repeat1] = STATE(3),
    [aux_sym_selection_statement_repeat1] = STATE(53),
    [anon_sym_if] = ACTIONS(3),
    [anon_sym_elif] = ACTIONS(21),
    [anon_sym_else] = ACTIONS(23),
    [anon_sym_endif] = ACTIONS(25),
    [sym__DECIMAL_NUMBER] = ACTIONS(5),
    [anon_sym_0o] = ACTIONS(7),
    [anon_sym_0x] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
  },
  [3] = {
    [sym_statement] = STATE(4),
    [sym_selection_statement] = STATE(116),
    [sym_expression] = STATE(116),
    [sym_literal] = STATE(126),
    [sym_integer_literal] = STATE(102),
    [sym_decimal_literal] = STATE(115),
    [sym_octal_literal] = STATE(115),
    [sym_hex_literal] = STATE(115),
    [sym_string_literal] = STATE(102),
    [sym_string_simple] = STATE(114),
    [sym_string_multiline] = STATE(114),
    [sym_boolean_literal] = STATE(102),
    [sym_array_literal] = STATE(102),
    [sym_dictionary_literal] = STATE(102),
    [aux_sym_build_definition_repeat1] = STATE(4),
    [aux_sym_selection_statement_repeat1] = STATE(36),
    [anon_sym_if] = ACTIONS(3),
    [anon_sym_elif] = ACTIONS(21),
    [anon_sym_else] = ACTIONS(27),
    [anon_sym_endif] = ACTIONS(29),
    [sym__DECIMAL_NUMBER] = ACTIONS(5),
    [anon_sym_0o] = ACTIONS(7),
    [anon_sym_0x] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
  },
  [4] = {
    [sym_statement] = STATE(4),
    [sym_selection_statement] = STATE(116),
    [sym_expression] = STATE(116),
    [sym_literal] = STATE(126),
    [sym_integer_literal] = STATE(102),
    [sym_decimal_literal] = STATE(115),
    [sym_octal_literal] = STATE(115),
    [sym_hex_literal] = STATE(115),
    [sym_string_literal] = STATE(102),
    [sym_string_simple] = STATE(114),
    [sym_string_multiline] = STATE(114),
    [sym_boolean_literal] = STATE(102),
    [sym_array_literal] = STATE(102),
    [sym_dictionary_literal] = STATE(102),
    [aux_sym_build_definition_repeat1] = STATE(4),
    [anon_sym_if] = ACTIONS(31),
    [anon_sym_elif] = ACTIONS(34),
    [anon_sym_else] = ACTIONS(34),
    [anon_sym_endif] = ACTIONS(34),
    [sym__DECIMAL_NUMBER] = ACTIONS(36),
    [anon_sym_0o] = ACTIONS(39),
    [anon_sym_0x] = ACTIONS(42),
    [anon_sym_SQUOTE] = ACTIONS(45),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(48),
    [anon_sym_true] = ACTIONS(51),
    [anon_sym_false] = ACTIONS(51),
    [anon_sym_LBRACK] = ACTIONS(54),
    [anon_sym_LBRACE] = ACTIONS(57),
  },
  [5] = {
    [sym_statement] = STATE(4),
    [sym_selection_statement] = STATE(116),
    [sym_expression] = STATE(116),
    [sym_literal] = STATE(126),
    [sym_integer_literal] = STATE(102),
    [sym_decimal_literal] = STATE(115),
    [sym_octal_literal] = STATE(115),
    [sym_hex_literal] = STATE(115),
    [sym_string_literal] = STATE(102),
    [sym_string_simple] = STATE(114),
    [sym_string_multiline] = STATE(114),
    [sym_boolean_literal] = STATE(102),
    [sym_array_literal] = STATE(102),
    [sym_dictionary_literal] = STATE(102),
    [aux_sym_build_definition_repeat1] = STATE(4),
    [anon_sym_if] = ACTIONS(3),
    [anon_sym_elif] = ACTIONS(60),
    [anon_sym_else] = ACTIONS(60),
    [anon_sym_endif] = ACTIONS(60),
    [sym__DECIMAL_NUMBER] = ACTIONS(5),
    [anon_sym_0o] = ACTIONS(7),
    [anon_sym_0x] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
  },
  [6] = {
    [sym_statement] = STATE(5),
    [sym_selection_statement] = STATE(116),
    [sym_expression] = STATE(116),
    [sym_literal] = STATE(126),
    [sym_integer_literal] = STATE(102),
    [sym_decimal_literal] = STATE(115),
    [sym_octal_literal] = STATE(115),
    [sym_hex_literal] = STATE(115),
    [sym_string_literal] = STATE(102),
    [sym_string_simple] = STATE(114),
    [sym_string_multiline] = STATE(114),
    [sym_boolean_literal] = STATE(102),
    [sym_array_literal] = STATE(102),
    [sym_dictionary_literal] = STATE(102),
    [aux_sym_build_definition_repeat1] = STATE(5),
    [anon_sym_if] = ACTIONS(3),
    [anon_sym_elif] = ACTIONS(62),
    [anon_sym_else] = ACTIONS(62),
    [anon_sym_endif] = ACTIONS(62),
    [sym__DECIMAL_NUMBER] = ACTIONS(5),
    [anon_sym_0o] = ACTIONS(7),
    [anon_sym_0x] = ACTIONS(9),
    [anon_sym_SQUOTE] = ACTIONS(11),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(13),
    [anon_sym_true] = ACTIONS(15),
    [anon_sym_false] = ACTIONS(15),
    [anon_sym_LBRACK] = ACTIONS(17),
    [anon_sym_LBRACE] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(7), 1,
      anon_sym_0o,
    ACTIONS(9), 1,
      anon_sym_0x,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_endif,
    STATE(126), 1,
      sym_literal,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(13), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(114), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(116), 2,
      sym_selection_statement,
      sym_expression,
    STATE(115), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(102), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [59] = 16,
    ACTIONS(31), 1,
      anon_sym_if,
    ACTIONS(34), 1,
      ts_builtin_sym_end,
    ACTIONS(36), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(39), 1,
      anon_sym_0o,
    ACTIONS(42), 1,
      anon_sym_0x,
    ACTIONS(45), 1,
      anon_sym_SQUOTE,
    ACTIONS(48), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(54), 1,
      anon_sym_LBRACK,
    ACTIONS(57), 1,
      anon_sym_LBRACE,
    STATE(126), 1,
      sym_literal,
    ACTIONS(51), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(8), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(114), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(127), 2,
      sym_selection_statement,
      sym_expression,
    STATE(115), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(102), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [118] = 16,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(7), 1,
      anon_sym_0o,
    ACTIONS(9), 1,
      anon_sym_0x,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(66), 1,
      anon_sym_endif,
    STATE(126), 1,
      sym_literal,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(114), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(116), 2,
      sym_selection_statement,
      sym_expression,
    STATE(115), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(102), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [177] = 16,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(7), 1,
      anon_sym_0o,
    ACTIONS(9), 1,
      anon_sym_0x,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_endif,
    STATE(126), 1,
      sym_literal,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(114), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(116), 2,
      sym_selection_statement,
      sym_expression,
    STATE(115), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(102), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [236] = 16,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(7), 1,
      anon_sym_0o,
    ACTIONS(9), 1,
      anon_sym_0x,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    STATE(126), 1,
      sym_literal,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(8), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(114), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(127), 2,
      sym_selection_statement,
      sym_expression,
    STATE(115), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(102), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [295] = 16,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(7), 1,
      anon_sym_0o,
    ACTIONS(9), 1,
      anon_sym_0x,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(29), 1,
      anon_sym_endif,
    STATE(126), 1,
      sym_literal,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(9), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(114), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(116), 2,
      sym_selection_statement,
      sym_expression,
    STATE(115), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(102), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [354] = 16,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(7), 1,
      anon_sym_0o,
    ACTIONS(9), 1,
      anon_sym_0x,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(70), 1,
      anon_sym_endif,
    STATE(126), 1,
      sym_literal,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(4), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(114), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(116), 2,
      sym_selection_statement,
      sym_expression,
    STATE(115), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(102), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [413] = 16,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(7), 1,
      anon_sym_0o,
    ACTIONS(9), 1,
      anon_sym_0x,
    ACTIONS(11), 1,
      anon_sym_SQUOTE,
    ACTIONS(13), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_LBRACE,
    ACTIONS(66), 1,
      anon_sym_endif,
    STATE(126), 1,
      sym_literal,
    ACTIONS(15), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(114), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(116), 2,
      sym_selection_statement,
      sym_expression,
    STATE(115), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(102), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [472] = 15,
    ACTIONS(72), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(74), 1,
      anon_sym_0o,
    ACTIONS(76), 1,
      anon_sym_0x,
    ACTIONS(78), 1,
      anon_sym_SQUOTE,
    ACTIONS(80), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    ACTIONS(86), 1,
      anon_sym_LBRACE,
    ACTIONS(88), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      sym_literal,
    STATE(75), 1,
      sym_key_value_item,
    STATE(109), 1,
      sym_expression,
    ACTIONS(82), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(56), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(57), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [526] = 15,
    ACTIONS(72), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(74), 1,
      anon_sym_0o,
    ACTIONS(76), 1,
      anon_sym_0x,
    ACTIONS(78), 1,
      anon_sym_SQUOTE,
    ACTIONS(80), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    ACTIONS(86), 1,
      anon_sym_LBRACE,
    ACTIONS(90), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      sym_literal,
    STATE(67), 1,
      sym_key_value_item,
    STATE(109), 1,
      sym_expression,
    ACTIONS(82), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(56), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(57), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [580] = 15,
    ACTIONS(72), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(74), 1,
      anon_sym_0o,
    ACTIONS(76), 1,
      anon_sym_0x,
    ACTIONS(78), 1,
      anon_sym_SQUOTE,
    ACTIONS(80), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    ACTIONS(86), 1,
      anon_sym_LBRACE,
    ACTIONS(92), 1,
      anon_sym_RBRACE,
    STATE(58), 1,
      sym_literal,
    STATE(71), 1,
      sym_key_value_item,
    STATE(109), 1,
      sym_expression,
    ACTIONS(82), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(56), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(57), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [634] = 14,
    ACTIONS(72), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(74), 1,
      anon_sym_0o,
    ACTIONS(76), 1,
      anon_sym_0x,
    ACTIONS(78), 1,
      anon_sym_SQUOTE,
    ACTIONS(80), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    ACTIONS(86), 1,
      anon_sym_LBRACE,
    ACTIONS(94), 1,
      anon_sym_RBRACK,
    STATE(58), 1,
      sym_literal,
    STATE(73), 1,
      sym_expression,
    ACTIONS(82), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(56), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(57), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [685] = 14,
    ACTIONS(72), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(74), 1,
      anon_sym_0o,
    ACTIONS(76), 1,
      anon_sym_0x,
    ACTIONS(78), 1,
      anon_sym_SQUOTE,
    ACTIONS(80), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    ACTIONS(86), 1,
      anon_sym_LBRACE,
    ACTIONS(96), 1,
      anon_sym_RBRACK,
    STATE(58), 1,
      sym_literal,
    STATE(68), 1,
      sym_expression,
    ACTIONS(82), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(56), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(57), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [736] = 14,
    ACTIONS(72), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(74), 1,
      anon_sym_0o,
    ACTIONS(76), 1,
      anon_sym_0x,
    ACTIONS(78), 1,
      anon_sym_SQUOTE,
    ACTIONS(80), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    ACTIONS(86), 1,
      anon_sym_LBRACE,
    ACTIONS(98), 1,
      anon_sym_RBRACK,
    STATE(58), 1,
      sym_literal,
    STATE(72), 1,
      sym_expression,
    ACTIONS(82), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(56), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(57), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [787] = 14,
    ACTIONS(72), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(74), 1,
      anon_sym_0o,
    ACTIONS(76), 1,
      anon_sym_0x,
    ACTIONS(78), 1,
      anon_sym_SQUOTE,
    ACTIONS(80), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    ACTIONS(86), 1,
      anon_sym_LBRACE,
    STATE(58), 1,
      sym_literal,
    STATE(96), 1,
      sym_key_value_item,
    STATE(109), 1,
      sym_expression,
    ACTIONS(82), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(56), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(57), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [838] = 14,
    ACTIONS(100), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(102), 1,
      anon_sym_0o,
    ACTIONS(104), 1,
      anon_sym_0x,
    ACTIONS(106), 1,
      anon_sym_SQUOTE,
    ACTIONS(108), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(112), 1,
      anon_sym_LBRACK,
    ACTIONS(114), 1,
      anon_sym_LBRACE,
    STATE(63), 1,
      sym_condition,
    STATE(80), 1,
      sym_expression,
    STATE(94), 1,
      sym_literal,
    ACTIONS(110), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(100), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(98), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(95), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [889] = 14,
    ACTIONS(100), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(102), 1,
      anon_sym_0o,
    ACTIONS(104), 1,
      anon_sym_0x,
    ACTIONS(106), 1,
      anon_sym_SQUOTE,
    ACTIONS(108), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(112), 1,
      anon_sym_LBRACK,
    ACTIONS(114), 1,
      anon_sym_LBRACE,
    STATE(74), 1,
      sym_condition,
    STATE(80), 1,
      sym_expression,
    STATE(94), 1,
      sym_literal,
    ACTIONS(110), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(100), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(98), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(95), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [940] = 13,
    ACTIONS(72), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(74), 1,
      anon_sym_0o,
    ACTIONS(76), 1,
      anon_sym_0x,
    ACTIONS(78), 1,
      anon_sym_SQUOTE,
    ACTIONS(80), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    ACTIONS(86), 1,
      anon_sym_LBRACE,
    STATE(58), 1,
      sym_literal,
    STATE(97), 1,
      sym_expression,
    ACTIONS(82), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(56), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(57), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [988] = 13,
    ACTIONS(72), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(74), 1,
      anon_sym_0o,
    ACTIONS(76), 1,
      anon_sym_0x,
    ACTIONS(78), 1,
      anon_sym_SQUOTE,
    ACTIONS(80), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(84), 1,
      anon_sym_LBRACK,
    ACTIONS(86), 1,
      anon_sym_LBRACE,
    STATE(58), 1,
      sym_literal,
    STATE(79), 1,
      sym_expression,
    ACTIONS(82), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(55), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(56), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(57), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1036] = 2,
    ACTIONS(118), 1,
      anon_sym_SQUOTE,
    ACTIONS(116), 12,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_endif,
      sym__DECIMAL_NUMBER,
      anon_sym_0o,
      anon_sym_0x,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [1054] = 2,
    ACTIONS(118), 1,
      anon_sym_SQUOTE,
    ACTIONS(116), 10,
      ts_builtin_sym_end,
      anon_sym_if,
      sym__DECIMAL_NUMBER,
      anon_sym_0o,
      anon_sym_0x,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [1070] = 4,
    ACTIONS(122), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(124), 1,
      aux_sym_string_multiline_token1,
    STATE(31), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(120), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1085] = 4,
    ACTIONS(128), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(130), 1,
      aux_sym_string_multiline_token1,
    STATE(30), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(126), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1100] = 4,
    ACTIONS(135), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(137), 1,
      aux_sym_string_multiline_token1,
    STATE(30), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(132), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1115] = 4,
    ACTIONS(130), 1,
      aux_sym_string_multiline_token1,
    ACTIONS(140), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    STATE(30), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(126), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1130] = 4,
    ACTIONS(144), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(146), 1,
      aux_sym_string_multiline_token1,
    STATE(29), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(142), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1145] = 4,
    ACTIONS(150), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(152), 1,
      aux_sym_string_multiline_token1,
    STATE(34), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(148), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1160] = 4,
    ACTIONS(130), 1,
      aux_sym_string_multiline_token1,
    ACTIONS(154), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    STATE(30), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(126), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1175] = 1,
    ACTIONS(156), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1182] = 4,
    ACTIONS(21), 1,
      anon_sym_elif,
    ACTIONS(66), 1,
      anon_sym_endif,
    ACTIONS(158), 1,
      anon_sym_else,
    STATE(61), 1,
      aux_sym_selection_statement_repeat1,
  [1195] = 4,
    ACTIONS(160), 1,
      sym_escape_sequence,
    ACTIONS(162), 1,
      anon_sym_SQUOTE,
    ACTIONS(164), 1,
      aux_sym_string_simple_token1,
    STATE(46), 1,
      aux_sym_string_simple_repeat1,
  [1208] = 4,
    ACTIONS(160), 1,
      sym_escape_sequence,
    ACTIONS(164), 1,
      aux_sym_string_simple_token1,
    ACTIONS(166), 1,
      anon_sym_SQUOTE,
    STATE(46), 1,
      aux_sym_string_simple_repeat1,
  [1221] = 4,
    ACTIONS(168), 1,
      sym_escape_sequence,
    ACTIONS(170), 1,
      anon_sym_SQUOTE,
    ACTIONS(172), 1,
      aux_sym_string_simple_token1,
    STATE(37), 1,
      aux_sym_string_simple_repeat1,
  [1234] = 4,
    ACTIONS(160), 1,
      sym_escape_sequence,
    ACTIONS(164), 1,
      aux_sym_string_simple_token1,
    ACTIONS(174), 1,
      anon_sym_SQUOTE,
    STATE(46), 1,
      aux_sym_string_simple_repeat1,
  [1247] = 4,
    ACTIONS(176), 1,
      sym_escape_sequence,
    ACTIONS(178), 1,
      anon_sym_SQUOTE,
    ACTIONS(180), 1,
      aux_sym_string_simple_token1,
    STATE(40), 1,
      aux_sym_string_simple_repeat1,
  [1260] = 1,
    ACTIONS(182), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1267] = 1,
    ACTIONS(184), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1274] = 1,
    ACTIONS(186), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1281] = 1,
    ACTIONS(188), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1288] = 4,
    ACTIONS(190), 1,
      sym_escape_sequence,
    ACTIONS(193), 1,
      anon_sym_SQUOTE,
    ACTIONS(195), 1,
      aux_sym_string_simple_token1,
    STATE(46), 1,
      aux_sym_string_simple_repeat1,
  [1301] = 1,
    ACTIONS(198), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1308] = 1,
    ACTIONS(200), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1315] = 1,
    ACTIONS(202), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1322] = 1,
    ACTIONS(204), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1329] = 1,
    ACTIONS(206), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1336] = 1,
    ACTIONS(208), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1343] = 4,
    ACTIONS(21), 1,
      anon_sym_elif,
    ACTIONS(27), 1,
      anon_sym_else,
    ACTIONS(29), 1,
      anon_sym_endif,
    STATE(61), 1,
      aux_sym_selection_statement_repeat1,
  [1356] = 1,
    ACTIONS(210), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1363] = 1,
    ACTIONS(212), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1370] = 1,
    ACTIONS(214), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1377] = 1,
    ACTIONS(216), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1384] = 1,
    ACTIONS(218), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1391] = 1,
    ACTIONS(220), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1398] = 1,
    ACTIONS(222), 4,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
      anon_sym_COLON,
  [1405] = 3,
    ACTIONS(224), 1,
      anon_sym_elif,
    STATE(61), 1,
      aux_sym_selection_statement_repeat1,
    ACTIONS(227), 2,
      anon_sym_else,
      anon_sym_endif,
  [1416] = 4,
    ACTIONS(229), 1,
      sym_escape_sequence,
    ACTIONS(231), 1,
      anon_sym_SQUOTE,
    ACTIONS(233), 1,
      aux_sym_string_simple_token1,
    STATE(38), 1,
      aux_sym_string_simple_repeat1,
  [1429] = 2,
    STATE(6), 1,
      sym__NEWLINE,
    ACTIONS(235), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1437] = 3,
    ACTIONS(237), 1,
      anon_sym_COMMA,
    ACTIONS(240), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_dictionary_literal_repeat1,
  [1447] = 3,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    ACTIONS(244), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_dictionary_literal_repeat1,
  [1457] = 3,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    ACTIONS(248), 1,
      anon_sym_RBRACK,
    STATE(78), 1,
      aux_sym_array_literal_repeat1,
  [1467] = 3,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    ACTIONS(250), 1,
      anon_sym_RBRACE,
    STATE(65), 1,
      aux_sym_dictionary_literal_repeat1,
  [1477] = 3,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    ACTIONS(252), 1,
      anon_sym_RBRACK,
    STATE(66), 1,
      aux_sym_array_literal_repeat1,
  [1487] = 3,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    ACTIONS(254), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_dictionary_literal_repeat1,
  [1497] = 3,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    ACTIONS(256), 1,
      anon_sym_RBRACK,
    STATE(78), 1,
      aux_sym_array_literal_repeat1,
  [1507] = 3,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    ACTIONS(258), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_dictionary_literal_repeat1,
  [1517] = 3,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    ACTIONS(260), 1,
      anon_sym_RBRACK,
    STATE(70), 1,
      aux_sym_array_literal_repeat1,
  [1527] = 3,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    ACTIONS(262), 1,
      anon_sym_RBRACK,
    STATE(76), 1,
      aux_sym_array_literal_repeat1,
  [1537] = 2,
    STATE(2), 1,
      sym__NEWLINE,
    ACTIONS(264), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1545] = 3,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    ACTIONS(266), 1,
      anon_sym_RBRACE,
    STATE(77), 1,
      aux_sym_dictionary_literal_repeat1,
  [1555] = 3,
    ACTIONS(246), 1,
      anon_sym_COMMA,
    ACTIONS(268), 1,
      anon_sym_RBRACK,
    STATE(78), 1,
      aux_sym_array_literal_repeat1,
  [1565] = 3,
    ACTIONS(242), 1,
      anon_sym_COMMA,
    ACTIONS(270), 1,
      anon_sym_RBRACE,
    STATE(64), 1,
      aux_sym_dictionary_literal_repeat1,
  [1575] = 3,
    ACTIONS(272), 1,
      anon_sym_COMMA,
    ACTIONS(275), 1,
      anon_sym_RBRACK,
    STATE(78), 1,
      aux_sym_array_literal_repeat1,
  [1585] = 1,
    ACTIONS(275), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1590] = 1,
    ACTIONS(277), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1595] = 1,
    ACTIONS(279), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1600] = 1,
    ACTIONS(281), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1605] = 1,
    ACTIONS(283), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1610] = 1,
    ACTIONS(285), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1615] = 1,
    ACTIONS(287), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1620] = 1,
    ACTIONS(289), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1625] = 1,
    ACTIONS(291), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1630] = 1,
    ACTIONS(293), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1635] = 1,
    ACTIONS(295), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1640] = 1,
    ACTIONS(297), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1645] = 1,
    ACTIONS(299), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1650] = 1,
    ACTIONS(301), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1655] = 1,
    ACTIONS(303), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1660] = 1,
    ACTIONS(305), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1665] = 1,
    ACTIONS(307), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1670] = 1,
    ACTIONS(240), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1675] = 1,
    ACTIONS(309), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [1680] = 1,
    ACTIONS(311), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1685] = 1,
    ACTIONS(313), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1690] = 1,
    ACTIONS(315), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [1695] = 1,
    ACTIONS(198), 1,
      anon_sym_LF,
  [1699] = 1,
    ACTIONS(216), 1,
      anon_sym_LF,
  [1703] = 1,
    ACTIONS(186), 1,
      anon_sym_LF,
  [1707] = 1,
    ACTIONS(220), 1,
      anon_sym_LF,
  [1711] = 1,
    ACTIONS(188), 1,
      anon_sym_LF,
  [1715] = 1,
    ACTIONS(317), 1,
      anon_sym_LF,
  [1719] = 1,
    ACTIONS(200), 1,
      anon_sym_LF,
  [1723] = 1,
    ACTIONS(210), 1,
      anon_sym_LF,
  [1727] = 1,
    ACTIONS(319), 1,
      anon_sym_COLON,
  [1731] = 1,
    ACTIONS(321), 1,
      sym__OCTAL_NUMBER,
  [1735] = 1,
    ACTIONS(323), 1,
      sym__HEX_NUMBER,
  [1739] = 1,
    ACTIONS(202), 1,
      anon_sym_LF,
  [1743] = 1,
    ACTIONS(184), 1,
      anon_sym_LF,
  [1747] = 1,
    ACTIONS(212), 1,
      anon_sym_LF,
  [1751] = 1,
    ACTIONS(214), 1,
      anon_sym_LF,
  [1755] = 1,
    ACTIONS(325), 1,
      anon_sym_LF,
  [1759] = 1,
    ACTIONS(182), 1,
      anon_sym_LF,
  [1763] = 1,
    ACTIONS(327), 1,
      anon_sym_LF,
  [1767] = 1,
    ACTIONS(329), 1,
      anon_sym_LF,
  [1771] = 1,
    ACTIONS(208), 1,
      anon_sym_LF,
  [1775] = 1,
    ACTIONS(222), 1,
      anon_sym_LF,
  [1779] = 1,
    ACTIONS(206), 1,
      anon_sym_LF,
  [1783] = 1,
    ACTIONS(331), 1,
      sym__OCTAL_NUMBER,
  [1787] = 1,
    ACTIONS(333), 1,
      sym__HEX_NUMBER,
  [1791] = 1,
    ACTIONS(204), 1,
      anon_sym_LF,
  [1795] = 1,
    ACTIONS(218), 1,
      anon_sym_LF,
  [1799] = 1,
    ACTIONS(335), 1,
      anon_sym_LF,
  [1803] = 1,
    ACTIONS(337), 1,
      ts_builtin_sym_end,
  [1807] = 1,
    ACTIONS(156), 1,
      anon_sym_LF,
  [1811] = 1,
    ACTIONS(339), 1,
      ts_builtin_sym_end,
  [1815] = 1,
    ACTIONS(341), 1,
      sym__OCTAL_NUMBER,
  [1819] = 1,
    ACTIONS(343), 1,
      sym__HEX_NUMBER,
  [1823] = 1,
    ACTIONS(345), 1,
      anon_sym_LF,
  [1827] = 1,
    ACTIONS(347), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 59,
  [SMALL_STATE(9)] = 118,
  [SMALL_STATE(10)] = 177,
  [SMALL_STATE(11)] = 236,
  [SMALL_STATE(12)] = 295,
  [SMALL_STATE(13)] = 354,
  [SMALL_STATE(14)] = 413,
  [SMALL_STATE(15)] = 472,
  [SMALL_STATE(16)] = 526,
  [SMALL_STATE(17)] = 580,
  [SMALL_STATE(18)] = 634,
  [SMALL_STATE(19)] = 685,
  [SMALL_STATE(20)] = 736,
  [SMALL_STATE(21)] = 787,
  [SMALL_STATE(22)] = 838,
  [SMALL_STATE(23)] = 889,
  [SMALL_STATE(24)] = 940,
  [SMALL_STATE(25)] = 988,
  [SMALL_STATE(26)] = 1036,
  [SMALL_STATE(27)] = 1054,
  [SMALL_STATE(28)] = 1070,
  [SMALL_STATE(29)] = 1085,
  [SMALL_STATE(30)] = 1100,
  [SMALL_STATE(31)] = 1115,
  [SMALL_STATE(32)] = 1130,
  [SMALL_STATE(33)] = 1145,
  [SMALL_STATE(34)] = 1160,
  [SMALL_STATE(35)] = 1175,
  [SMALL_STATE(36)] = 1182,
  [SMALL_STATE(37)] = 1195,
  [SMALL_STATE(38)] = 1208,
  [SMALL_STATE(39)] = 1221,
  [SMALL_STATE(40)] = 1234,
  [SMALL_STATE(41)] = 1247,
  [SMALL_STATE(42)] = 1260,
  [SMALL_STATE(43)] = 1267,
  [SMALL_STATE(44)] = 1274,
  [SMALL_STATE(45)] = 1281,
  [SMALL_STATE(46)] = 1288,
  [SMALL_STATE(47)] = 1301,
  [SMALL_STATE(48)] = 1308,
  [SMALL_STATE(49)] = 1315,
  [SMALL_STATE(50)] = 1322,
  [SMALL_STATE(51)] = 1329,
  [SMALL_STATE(52)] = 1336,
  [SMALL_STATE(53)] = 1343,
  [SMALL_STATE(54)] = 1356,
  [SMALL_STATE(55)] = 1363,
  [SMALL_STATE(56)] = 1370,
  [SMALL_STATE(57)] = 1377,
  [SMALL_STATE(58)] = 1384,
  [SMALL_STATE(59)] = 1391,
  [SMALL_STATE(60)] = 1398,
  [SMALL_STATE(61)] = 1405,
  [SMALL_STATE(62)] = 1416,
  [SMALL_STATE(63)] = 1429,
  [SMALL_STATE(64)] = 1437,
  [SMALL_STATE(65)] = 1447,
  [SMALL_STATE(66)] = 1457,
  [SMALL_STATE(67)] = 1467,
  [SMALL_STATE(68)] = 1477,
  [SMALL_STATE(69)] = 1487,
  [SMALL_STATE(70)] = 1497,
  [SMALL_STATE(71)] = 1507,
  [SMALL_STATE(72)] = 1517,
  [SMALL_STATE(73)] = 1527,
  [SMALL_STATE(74)] = 1537,
  [SMALL_STATE(75)] = 1545,
  [SMALL_STATE(76)] = 1555,
  [SMALL_STATE(77)] = 1565,
  [SMALL_STATE(78)] = 1575,
  [SMALL_STATE(79)] = 1585,
  [SMALL_STATE(80)] = 1590,
  [SMALL_STATE(81)] = 1595,
  [SMALL_STATE(82)] = 1600,
  [SMALL_STATE(83)] = 1605,
  [SMALL_STATE(84)] = 1610,
  [SMALL_STATE(85)] = 1615,
  [SMALL_STATE(86)] = 1620,
  [SMALL_STATE(87)] = 1625,
  [SMALL_STATE(88)] = 1630,
  [SMALL_STATE(89)] = 1635,
  [SMALL_STATE(90)] = 1640,
  [SMALL_STATE(91)] = 1645,
  [SMALL_STATE(92)] = 1650,
  [SMALL_STATE(93)] = 1655,
  [SMALL_STATE(94)] = 1660,
  [SMALL_STATE(95)] = 1665,
  [SMALL_STATE(96)] = 1670,
  [SMALL_STATE(97)] = 1675,
  [SMALL_STATE(98)] = 1680,
  [SMALL_STATE(99)] = 1685,
  [SMALL_STATE(100)] = 1690,
  [SMALL_STATE(101)] = 1695,
  [SMALL_STATE(102)] = 1699,
  [SMALL_STATE(103)] = 1703,
  [SMALL_STATE(104)] = 1707,
  [SMALL_STATE(105)] = 1711,
  [SMALL_STATE(106)] = 1715,
  [SMALL_STATE(107)] = 1719,
  [SMALL_STATE(108)] = 1723,
  [SMALL_STATE(109)] = 1727,
  [SMALL_STATE(110)] = 1731,
  [SMALL_STATE(111)] = 1735,
  [SMALL_STATE(112)] = 1739,
  [SMALL_STATE(113)] = 1743,
  [SMALL_STATE(114)] = 1747,
  [SMALL_STATE(115)] = 1751,
  [SMALL_STATE(116)] = 1755,
  [SMALL_STATE(117)] = 1759,
  [SMALL_STATE(118)] = 1763,
  [SMALL_STATE(119)] = 1767,
  [SMALL_STATE(120)] = 1771,
  [SMALL_STATE(121)] = 1775,
  [SMALL_STATE(122)] = 1779,
  [SMALL_STATE(123)] = 1783,
  [SMALL_STATE(124)] = 1787,
  [SMALL_STATE(125)] = 1791,
  [SMALL_STATE(126)] = 1795,
  [SMALL_STATE(127)] = 1799,
  [SMALL_STATE(128)] = 1803,
  [SMALL_STATE(129)] = 1807,
  [SMALL_STATE(130)] = 1811,
  [SMALL_STATE(131)] = 1815,
  [SMALL_STATE(132)] = 1819,
  [SMALL_STATE(133)] = 1823,
  [SMALL_STATE(134)] = 1827,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(23),
  [34] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(121),
  [39] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(131),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(132),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(62),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(32),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(104),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(18),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(15),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selection_statement_repeat1, 4),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selection_statement_repeat1, 3),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_build_definition, 1),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [78] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [84] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(101),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [132] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_multiline_repeat1, 2), SHIFT_REPEAT(30),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_multiline_repeat1, 2),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_multiline_repeat1, 2), SHIFT_REPEAT(30),
  [140] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [144] = {.entry = {.count = 1, .reusable = false}}, SHIFT(129),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [154] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_multiline, 2),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [160] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [162] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(107),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [174] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [178] = {.entry = {.count = 1, .reusable = false}}, SHIFT(82),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary_literal, 4),
  [184] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 4),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary_literal, 3),
  [188] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 3),
  [190] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_simple_repeat1, 2), SHIFT_REPEAT(46),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_simple_repeat1, 2),
  [195] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_simple_repeat1, 2), SHIFT_REPEAT(46),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_multiline, 3),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_simple, 3),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary_literal, 2),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 2),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_simple, 2),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hex_literal, 2),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_octal_literal, 2),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 1),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer_literal, 1),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decimal_literal, 1),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_selection_statement_repeat1, 2), SHIFT_REPEAT(22),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selection_statement_repeat1, 2),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [231] = {.entry = {.count = 1, .reusable = false}}, SHIFT(122),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [235] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [237] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dictionary_literal_repeat1, 2), SHIFT_REPEAT(21),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dictionary_literal_repeat1, 2),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [264] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [272] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2), SHIFT_REPEAT(25),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2),
  [277] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_condition, 1),
  [279] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hex_literal, 2),
  [281] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_simple, 2),
  [283] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_multiline, 2),
  [285] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 2),
  [287] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary_literal, 2),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1),
  [291] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decimal_literal, 1),
  [293] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_simple, 3),
  [295] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_multiline, 3),
  [297] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 3),
  [299] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary_literal, 3),
  [301] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 4),
  [303] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary_literal, 4),
  [305] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [307] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1),
  [309] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value_item, 3, .production_id = 1),
  [311] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer_literal, 1),
  [313] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_octal_literal, 2),
  [315] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 1),
  [317] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 4),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [327] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 5),
  [329] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 8),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [339] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [345] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 6),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 7),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_meson(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
