#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 153
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 63
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 2

enum {
  anon_sym_LF = 1,
  anon_sym_if = 2,
  anon_sym_elif = 3,
  anon_sym_else = 4,
  anon_sym_endif = 5,
  anon_sym_foreach = 6,
  anon_sym_COLON = 7,
  anon_sym_endforeach = 8,
  anon_sym_break = 9,
  anon_sym_continue = 10,
  sym__DECIMAL_NUMBER = 11,
  anon_sym_0o = 12,
  sym__OCTAL_NUMBER = 13,
  anon_sym_0x = 14,
  sym__HEX_NUMBER = 15,
  sym_escape_sequence = 16,
  anon_sym_SQUOTE = 17,
  aux_sym_string_simple_token1 = 18,
  anon_sym_SQUOTE_SQUOTE_SQUOTE = 19,
  aux_sym_string_multiline_token1 = 20,
  anon_sym_SQUOTE_SQUOTE = 21,
  anon_sym_true = 22,
  anon_sym_false = 23,
  anon_sym_LBRACK = 24,
  anon_sym_COMMA = 25,
  anon_sym_RBRACK = 26,
  anon_sym_LF2 = 27,
  anon_sym_CR_LF = 28,
  anon_sym_LBRACE = 29,
  anon_sym_RBRACE = 30,
  sym__IDENTIFIER = 31,
  sym_source_file = 32,
  sym_build_definition = 33,
  sym_statement = 34,
  sym_selection_statement = 35,
  sym_iteration_statement = 36,
  sym_jump_statement = 37,
  sym_condition = 38,
  sym_expression = 39,
  sym_literal = 40,
  sym_integer_literal = 41,
  sym_decimal_literal = 42,
  sym_octal_literal = 43,
  sym_hex_literal = 44,
  sym_string_literal = 45,
  sym_string_simple = 46,
  sym_string_multiline = 47,
  sym_boolean_literal = 48,
  sym_array_literal = 49,
  sym__NEWLINE = 50,
  sym_dictionary_literal = 51,
  sym_key_value_item = 52,
  sym_identifier_list = 53,
  sym_id_expression = 54,
  aux_sym_build_definition_repeat1 = 55,
  aux_sym_selection_statement_repeat1 = 56,
  aux_sym_iteration_statement_repeat1 = 57,
  aux_sym_string_simple_repeat1 = 58,
  aux_sym_string_multiline_repeat1 = 59,
  aux_sym_array_literal_repeat1 = 60,
  aux_sym_dictionary_literal_repeat1 = 61,
  aux_sym_identifier_list_repeat1 = 62,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_if] = "if",
  [anon_sym_elif] = "elif",
  [anon_sym_else] = "else",
  [anon_sym_endif] = "endif",
  [anon_sym_foreach] = "foreach",
  [anon_sym_COLON] = ":",
  [anon_sym_endforeach] = "endforeach",
  [anon_sym_break] = "break",
  [anon_sym_continue] = "continue",
  [sym__DECIMAL_NUMBER] = "_DECIMAL_NUMBER",
  [anon_sym_0o] = "0o",
  [sym__OCTAL_NUMBER] = "_OCTAL_NUMBER",
  [anon_sym_0x] = "0x",
  [sym__HEX_NUMBER] = "_HEX_NUMBER",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_simple_token1] = "string_simple_token1",
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = "'''",
  [aux_sym_string_multiline_token1] = "string_multiline_token1",
  [anon_sym_SQUOTE_SQUOTE] = "''",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LF2] = "\n",
  [anon_sym_CR_LF] = "\r\n",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym__IDENTIFIER] = "_IDENTIFIER",
  [sym_source_file] = "source_file",
  [sym_build_definition] = "build_definition",
  [sym_statement] = "statement",
  [sym_selection_statement] = "selection_statement",
  [sym_iteration_statement] = "iteration_statement",
  [sym_jump_statement] = "jump_statement",
  [sym_condition] = "condition",
  [sym_expression] = "expression",
  [sym_literal] = "literal",
  [sym_integer_literal] = "integer_literal",
  [sym_decimal_literal] = "decimal_literal",
  [sym_octal_literal] = "octal_literal",
  [sym_hex_literal] = "hex_literal",
  [sym_string_literal] = "string_literal",
  [sym_string_simple] = "string_simple",
  [sym_string_multiline] = "string_multiline",
  [sym_boolean_literal] = "boolean_literal",
  [sym_array_literal] = "array_literal",
  [sym__NEWLINE] = "_NEWLINE",
  [sym_dictionary_literal] = "dictionary_literal",
  [sym_key_value_item] = "key_value_item",
  [sym_identifier_list] = "identifier_list",
  [sym_id_expression] = "id_expression",
  [aux_sym_build_definition_repeat1] = "build_definition_repeat1",
  [aux_sym_selection_statement_repeat1] = "selection_statement_repeat1",
  [aux_sym_iteration_statement_repeat1] = "iteration_statement_repeat1",
  [aux_sym_string_simple_repeat1] = "string_simple_repeat1",
  [aux_sym_string_multiline_repeat1] = "string_multiline_repeat1",
  [aux_sym_array_literal_repeat1] = "array_literal_repeat1",
  [aux_sym_dictionary_literal_repeat1] = "dictionary_literal_repeat1",
  [aux_sym_identifier_list_repeat1] = "identifier_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elif] = anon_sym_elif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_endif] = anon_sym_endif,
  [anon_sym_foreach] = anon_sym_foreach,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_endforeach] = anon_sym_endforeach,
  [anon_sym_break] = anon_sym_break,
  [anon_sym_continue] = anon_sym_continue,
  [sym__DECIMAL_NUMBER] = sym__DECIMAL_NUMBER,
  [anon_sym_0o] = anon_sym_0o,
  [sym__OCTAL_NUMBER] = sym__OCTAL_NUMBER,
  [anon_sym_0x] = anon_sym_0x,
  [sym__HEX_NUMBER] = sym__HEX_NUMBER,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_simple_token1] = aux_sym_string_simple_token1,
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = anon_sym_SQUOTE_SQUOTE_SQUOTE,
  [aux_sym_string_multiline_token1] = aux_sym_string_multiline_token1,
  [anon_sym_SQUOTE_SQUOTE] = anon_sym_SQUOTE_SQUOTE,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LF2] = anon_sym_LF,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym__IDENTIFIER] = sym__IDENTIFIER,
  [sym_source_file] = sym_source_file,
  [sym_build_definition] = sym_build_definition,
  [sym_statement] = sym_statement,
  [sym_selection_statement] = sym_selection_statement,
  [sym_iteration_statement] = sym_iteration_statement,
  [sym_jump_statement] = sym_jump_statement,
  [sym_condition] = sym_condition,
  [sym_expression] = sym_expression,
  [sym_literal] = sym_literal,
  [sym_integer_literal] = sym_integer_literal,
  [sym_decimal_literal] = sym_decimal_literal,
  [sym_octal_literal] = sym_octal_literal,
  [sym_hex_literal] = sym_hex_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_string_simple] = sym_string_simple,
  [sym_string_multiline] = sym_string_multiline,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_array_literal] = sym_array_literal,
  [sym__NEWLINE] = sym__NEWLINE,
  [sym_dictionary_literal] = sym_dictionary_literal,
  [sym_key_value_item] = sym_key_value_item,
  [sym_identifier_list] = sym_identifier_list,
  [sym_id_expression] = sym_id_expression,
  [aux_sym_build_definition_repeat1] = aux_sym_build_definition_repeat1,
  [aux_sym_selection_statement_repeat1] = aux_sym_selection_statement_repeat1,
  [aux_sym_iteration_statement_repeat1] = aux_sym_iteration_statement_repeat1,
  [aux_sym_string_simple_repeat1] = aux_sym_string_simple_repeat1,
  [aux_sym_string_multiline_repeat1] = aux_sym_string_multiline_repeat1,
  [aux_sym_array_literal_repeat1] = aux_sym_array_literal_repeat1,
  [aux_sym_dictionary_literal_repeat1] = aux_sym_dictionary_literal_repeat1,
  [aux_sym_identifier_list_repeat1] = aux_sym_identifier_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_foreach] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endforeach] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_continue] = {
    .visible = true,
    .named = false,
  },
  [sym__DECIMAL_NUMBER] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_0o] = {
    .visible = true,
    .named = false,
  },
  [sym__OCTAL_NUMBER] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_0x] = {
    .visible = true,
    .named = false,
  },
  [sym__HEX_NUMBER] = {
    .visible = false,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_simple_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_multiline_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__IDENTIFIER] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_build_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_selection_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_iteration_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_jump_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_decimal_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_octal_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_simple] = {
    .visible = true,
    .named = true,
  },
  [sym_string_multiline] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_array_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__NEWLINE] = {
    .visible = false,
    .named = true,
  },
  [sym_dictionary_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_key_value_item] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_list] = {
    .visible = true,
    .named = true,
  },
  [sym_id_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_build_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_selection_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_iteration_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_simple_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_multiline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dictionary_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_key = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(56);
      if (lookahead == '\'') ADVANCE(85);
      if (lookahead == ',') ADVANCE(96);
      if (lookahead == '0') ADVANCE(67);
      if (lookahead == ':') ADVANCE(63);
      if (lookahead == '[') ADVANCE(95);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == ']') ADVANCE(97);
      if (lookahead == 'b') ADVANCE(79);
      if (lookahead == 'c') ADVANCE(78);
      if (lookahead == 'e') ADVANCE(76);
      if (lookahead == 'f') ADVANCE(75);
      if (lookahead == 'i') ADVANCE(22);
      if (lookahead == 't') ADVANCE(38);
      if (lookahead == '{') ADVANCE(99);
      if (lookahead == '}') ADVANCE(100);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(70);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '7')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'd')) ADVANCE(80);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(6)
      if (lookahead == '\'') ADVANCE(84);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0) ADVANCE(88);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2)
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(57);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(85);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(90);
      if (lookahead != 0) ADVANCE(91);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(89);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(84);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(6)
      END_STATE();
    case 7:
      if (lookahead == 'U') ADVANCE(54);
      if (lookahead == 'u') ADVANCE(50);
      if (lookahead == 'x') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      if (lookahead != 0) ADVANCE(81);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(12);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(32);
      if (lookahead == 'o') ADVANCE(39);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(26);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(24);
      END_STATE();
    case 15:
      if (lookahead == 'e') ADVANCE(8);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(93);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(94);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(11);
      END_STATE();
    case 22:
      if (lookahead == 'f') ADVANCE(58);
      END_STATE();
    case 23:
      if (lookahead == 'f') ADVANCE(59);
      END_STATE();
    case 24:
      if (lookahead == 'f') ADVANCE(36);
      if (lookahead == 'i') ADVANCE(25);
      END_STATE();
    case 25:
      if (lookahead == 'f') ADVANCE(61);
      END_STATE();
    case 26:
      if (lookahead == 'h') ADVANCE(62);
      END_STATE();
    case 27:
      if (lookahead == 'h') ADVANCE(64);
      END_STATE();
    case 28:
      if (lookahead == 'i') ADVANCE(23);
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(34);
      END_STATE();
    case 30:
      if (lookahead == 'k') ADVANCE(65);
      END_STATE();
    case 31:
      if (lookahead == 'l') ADVANCE(28);
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(41);
      END_STATE();
    case 33:
      if (lookahead == 'n') ADVANCE(42);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(44);
      END_STATE();
    case 35:
      if (lookahead == 'o') ADVANCE(33);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 37:
      if (lookahead == 'r') ADVANCE(15);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(43);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(20);
      END_STATE();
    case 40:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 41:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 43:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 44:
      if (lookahead == 'u') ADVANCE(19);
      END_STATE();
    case 45:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(45)
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(73);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    case 46:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(46)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(80);
      END_STATE();
    case 47:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(81);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(47);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(48);
      END_STATE();
    case 50:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(49);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(50);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(51);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(53);
      END_STATE();
    case 55:
      if (eof) ADVANCE(56);
      if (lookahead == '\'') ADVANCE(86);
      if (lookahead == '0') ADVANCE(68);
      if (lookahead == '[') ADVANCE(95);
      if (lookahead == ']') ADVANCE(97);
      if (lookahead == 'b') ADVANCE(37);
      if (lookahead == 'c') ADVANCE(35);
      if (lookahead == 'e') ADVANCE(31);
      if (lookahead == 'f') ADVANCE(10);
      if (lookahead == 'i') ADVANCE(22);
      if (lookahead == 't') ADVANCE(38);
      if (lookahead == '{') ADVANCE(99);
      if (lookahead == '}') ADVANCE(100);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(55)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_elif);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_endif);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_foreach);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_endforeach);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_break);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_continue);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym__DECIMAL_NUMBER);
      if (lookahead == 'o') ADVANCE(72);
      if (lookahead == 'x') ADVANCE(74);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(80);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym__DECIMAL_NUMBER);
      if (lookahead == 'o') ADVANCE(72);
      if (lookahead == 'x') ADVANCE(74);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym__DECIMAL_NUMBER);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(80);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym__DECIMAL_NUMBER);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(70);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(80);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__DECIMAL_NUMBER);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(anon_sym_0o);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym__OCTAL_NUMBER);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_0x);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym__HEX_NUMBER);
      if (lookahead == 'a') ADVANCE(77);
      if (lookahead == 'o') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('b' <= lookahead && lookahead <= 'f')) ADVANCE(80);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym__HEX_NUMBER);
      if (lookahead == 'l') ADVANCE(28);
      if (lookahead == 'n') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(80);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym__HEX_NUMBER);
      if (lookahead == 'l') ADVANCE(41);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(80);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym__HEX_NUMBER);
      if (lookahead == 'o') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(80);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym__HEX_NUMBER);
      if (lookahead == 'r') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(80);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym__HEX_NUMBER);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(80);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(81);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '\'') ADVANCE(92);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '\'') ADVANCE(5);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_string_simple_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(88);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_string_simple_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(88);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(anon_sym_SQUOTE_SQUOTE_SQUOTE);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_string_multiline_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(91);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_string_multiline_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(91);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_SQUOTE_SQUOTE);
      if (lookahead == '\'') ADVANCE(89);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_LF2);
      if (lookahead == '\n') ADVANCE(98);
      if (lookahead == '\r') ADVANCE(2);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym__IDENTIFIER);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(101);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 55},
  [2] = {.lex_state = 55},
  [3] = {.lex_state = 55},
  [4] = {.lex_state = 55},
  [5] = {.lex_state = 55},
  [6] = {.lex_state = 55},
  [7] = {.lex_state = 55},
  [8] = {.lex_state = 55},
  [9] = {.lex_state = 55},
  [10] = {.lex_state = 55},
  [11] = {.lex_state = 55},
  [12] = {.lex_state = 55},
  [13] = {.lex_state = 55},
  [14] = {.lex_state = 55},
  [15] = {.lex_state = 55},
  [16] = {.lex_state = 55},
  [17] = {.lex_state = 55},
  [18] = {.lex_state = 55},
  [19] = {.lex_state = 55},
  [20] = {.lex_state = 55},
  [21] = {.lex_state = 55},
  [22] = {.lex_state = 55},
  [23] = {.lex_state = 55},
  [24] = {.lex_state = 55},
  [25] = {.lex_state = 55},
  [26] = {.lex_state = 55},
  [27] = {.lex_state = 55},
  [28] = {.lex_state = 55},
  [29] = {.lex_state = 55},
  [30] = {.lex_state = 55},
  [31] = {.lex_state = 55},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 4},
  [34] = {.lex_state = 4},
  [35] = {.lex_state = 4},
  [36] = {.lex_state = 4},
  [37] = {.lex_state = 4},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 55},
  [59] = {.lex_state = 55},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 55},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 2},
  [73] = {.lex_state = 2},
  [74] = {.lex_state = 2},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 2},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 45},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 2},
  [92] = {.lex_state = 2},
  [93] = {.lex_state = 2},
  [94] = {.lex_state = 2},
  [95] = {.lex_state = 45},
  [96] = {.lex_state = 2},
  [97] = {.lex_state = 2},
  [98] = {.lex_state = 2},
  [99] = {.lex_state = 2},
  [100] = {.lex_state = 2},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 45},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 2},
  [105] = {.lex_state = 2},
  [106] = {.lex_state = 2},
  [107] = {.lex_state = 2},
  [108] = {.lex_state = 2},
  [109] = {.lex_state = 2},
  [110] = {.lex_state = 2},
  [111] = {.lex_state = 2},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 2},
  [115] = {.lex_state = 2},
  [116] = {.lex_state = 3},
  [117] = {.lex_state = 3},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 3},
  [120] = {.lex_state = 46},
  [121] = {.lex_state = 3},
  [122] = {.lex_state = 3},
  [123] = {.lex_state = 3},
  [124] = {.lex_state = 3},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 3},
  [127] = {.lex_state = 3},
  [128] = {.lex_state = 45},
  [129] = {.lex_state = 46},
  [130] = {.lex_state = 3},
  [131] = {.lex_state = 3},
  [132] = {.lex_state = 3},
  [133] = {.lex_state = 3},
  [134] = {.lex_state = 3},
  [135] = {.lex_state = 3},
  [136] = {.lex_state = 3},
  [137] = {.lex_state = 3},
  [138] = {.lex_state = 3},
  [139] = {.lex_state = 3},
  [140] = {.lex_state = 3},
  [141] = {.lex_state = 45},
  [142] = {.lex_state = 46},
  [143] = {.lex_state = 45},
  [144] = {.lex_state = 3},
  [145] = {.lex_state = 3},
  [146] = {.lex_state = 3},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 3},
  [150] = {.lex_state = 3},
  [151] = {.lex_state = 3},
  [152] = {.lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_endif] = ACTIONS(1),
    [anon_sym_foreach] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_endforeach] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [anon_sym_continue] = ACTIONS(1),
    [sym__DECIMAL_NUMBER] = ACTIONS(1),
    [anon_sym_0o] = ACTIONS(1),
    [sym__OCTAL_NUMBER] = ACTIONS(1),
    [anon_sym_0x] = ACTIONS(1),
    [sym__HEX_NUMBER] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE_SQUOTE] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(118),
    [sym_build_definition] = STATE(148),
    [sym_statement] = STATE(13),
    [sym_selection_statement] = STATE(146),
    [sym_iteration_statement] = STATE(146),
    [sym_expression] = STATE(146),
    [sym_literal] = STATE(145),
    [sym_integer_literal] = STATE(144),
    [sym_decimal_literal] = STATE(136),
    [sym_octal_literal] = STATE(136),
    [sym_hex_literal] = STATE(136),
    [sym_string_literal] = STATE(144),
    [sym_string_simple] = STATE(119),
    [sym_string_multiline] = STATE(119),
    [sym_boolean_literal] = STATE(144),
    [sym_array_literal] = STATE(144),
    [sym_dictionary_literal] = STATE(144),
    [aux_sym_build_definition_repeat1] = STATE(13),
    [anon_sym_if] = ACTIONS(3),
    [anon_sym_foreach] = ACTIONS(5),
    [sym__DECIMAL_NUMBER] = ACTIONS(7),
    [anon_sym_0o] = ACTIONS(9),
    [anon_sym_0x] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 20,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_elif,
    ACTIONS(25), 1,
      anon_sym_else,
    ACTIONS(27), 1,
      anon_sym_endif,
    STATE(61), 1,
      aux_sym_selection_statement_repeat1,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(6), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [72] = 18,
    ACTIONS(29), 1,
      anon_sym_if,
    ACTIONS(32), 1,
      anon_sym_foreach,
    ACTIONS(35), 1,
      anon_sym_endforeach,
    ACTIONS(40), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(43), 1,
      anon_sym_0o,
    ACTIONS(46), 1,
      anon_sym_0x,
    ACTIONS(49), 1,
      anon_sym_SQUOTE,
    ACTIONS(52), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(58), 1,
      anon_sym_LBRACK,
    ACTIONS(61), 1,
      anon_sym_LBRACE,
    STATE(145), 1,
      sym_literal,
    ACTIONS(37), 2,
      anon_sym_break,
      anon_sym_continue,
    ACTIONS(55), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(3), 3,
      sym_statement,
      sym_jump_statement,
      aux_sym_iteration_statement_repeat1,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [140] = 18,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(64), 1,
      anon_sym_endforeach,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(66), 2,
      anon_sym_break,
      anon_sym_continue,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(3), 3,
      sym_statement,
      sym_jump_statement,
      aux_sym_iteration_statement_repeat1,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [208] = 18,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(68), 1,
      anon_sym_endforeach,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(66), 2,
      anon_sym_break,
      anon_sym_continue,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(4), 3,
      sym_statement,
      sym_jump_statement,
      aux_sym_iteration_statement_repeat1,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [276] = 20,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      anon_sym_elif,
    ACTIONS(70), 1,
      anon_sym_else,
    ACTIONS(72), 1,
      anon_sym_endif,
    STATE(59), 1,
      aux_sym_selection_statement_repeat1,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [348] = 17,
    ACTIONS(74), 1,
      anon_sym_if,
    ACTIONS(79), 1,
      anon_sym_foreach,
    ACTIONS(82), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(85), 1,
      anon_sym_0o,
    ACTIONS(88), 1,
      anon_sym_0x,
    ACTIONS(91), 1,
      anon_sym_SQUOTE,
    ACTIONS(94), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(100), 1,
      anon_sym_LBRACK,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    STATE(145), 1,
      sym_literal,
    ACTIONS(97), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    ACTIONS(77), 3,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_endif,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [413] = 17,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    ACTIONS(106), 3,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_endif,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [478] = 17,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(8), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    ACTIONS(108), 3,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_endif,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [543] = 17,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(110), 1,
      anon_sym_endif,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [606] = 17,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(72), 1,
      anon_sym_endif,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(16), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [669] = 17,
    ACTIONS(74), 1,
      anon_sym_if,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 1,
      anon_sym_foreach,
    ACTIONS(82), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(85), 1,
      anon_sym_0o,
    ACTIONS(88), 1,
      anon_sym_0x,
    ACTIONS(91), 1,
      anon_sym_SQUOTE,
    ACTIONS(94), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(100), 1,
      anon_sym_LBRACK,
    ACTIONS(103), 1,
      anon_sym_LBRACE,
    STATE(145), 1,
      sym_literal,
    ACTIONS(97), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(146), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [732] = 17,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(112), 1,
      ts_builtin_sym_end,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(146), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [795] = 17,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(110), 1,
      anon_sym_endif,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(15), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [858] = 17,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(114), 1,
      anon_sym_endif,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [921] = 17,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_endif,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [984] = 17,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(116), 1,
      anon_sym_endif,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1047] = 15,
    ACTIONS(118), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(120), 1,
      anon_sym_0o,
    ACTIONS(122), 1,
      anon_sym_0x,
    ACTIONS(124), 1,
      anon_sym_SQUOTE,
    ACTIONS(126), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(130), 1,
      anon_sym_LBRACK,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    ACTIONS(134), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      sym_literal,
    STATE(83), 1,
      sym_key_value_item,
    STATE(147), 1,
      sym_expression,
    ACTIONS(128), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1101] = 15,
    ACTIONS(118), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(120), 1,
      anon_sym_0o,
    ACTIONS(122), 1,
      anon_sym_0x,
    ACTIONS(124), 1,
      anon_sym_SQUOTE,
    ACTIONS(126), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(130), 1,
      anon_sym_LBRACK,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    ACTIONS(136), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      sym_literal,
    STATE(87), 1,
      sym_key_value_item,
    STATE(147), 1,
      sym_expression,
    ACTIONS(128), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1155] = 15,
    ACTIONS(118), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(120), 1,
      anon_sym_0o,
    ACTIONS(122), 1,
      anon_sym_0x,
    ACTIONS(124), 1,
      anon_sym_SQUOTE,
    ACTIONS(126), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(130), 1,
      anon_sym_LBRACK,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    ACTIONS(138), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      sym_literal,
    STATE(79), 1,
      sym_key_value_item,
    STATE(147), 1,
      sym_expression,
    ACTIONS(128), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1209] = 14,
    ACTIONS(118), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(120), 1,
      anon_sym_0o,
    ACTIONS(122), 1,
      anon_sym_0x,
    ACTIONS(124), 1,
      anon_sym_SQUOTE,
    ACTIONS(126), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(130), 1,
      anon_sym_LBRACK,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    ACTIONS(140), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      sym_literal,
    STATE(86), 1,
      sym_expression,
    ACTIONS(128), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1260] = 14,
    ACTIONS(142), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(144), 1,
      anon_sym_0o,
    ACTIONS(146), 1,
      anon_sym_0x,
    ACTIONS(148), 1,
      anon_sym_SQUOTE,
    ACTIONS(150), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(154), 1,
      anon_sym_LBRACK,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    STATE(74), 1,
      sym_condition,
    STATE(91), 1,
      sym_literal,
    STATE(111), 1,
      sym_expression,
    ACTIONS(152), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(94), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(93), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(92), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1311] = 14,
    ACTIONS(118), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(120), 1,
      anon_sym_0o,
    ACTIONS(122), 1,
      anon_sym_0x,
    ACTIONS(124), 1,
      anon_sym_SQUOTE,
    ACTIONS(126), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(130), 1,
      anon_sym_LBRACK,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    ACTIONS(158), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      sym_literal,
    STATE(78), 1,
      sym_expression,
    ACTIONS(128), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1362] = 14,
    ACTIONS(118), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(120), 1,
      anon_sym_0o,
    ACTIONS(122), 1,
      anon_sym_0x,
    ACTIONS(124), 1,
      anon_sym_SQUOTE,
    ACTIONS(126), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(130), 1,
      anon_sym_LBRACK,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    ACTIONS(160), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      sym_literal,
    STATE(85), 1,
      sym_expression,
    ACTIONS(128), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1413] = 14,
    ACTIONS(118), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(120), 1,
      anon_sym_0o,
    ACTIONS(122), 1,
      anon_sym_0x,
    ACTIONS(124), 1,
      anon_sym_SQUOTE,
    ACTIONS(126), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(130), 1,
      anon_sym_LBRACK,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_literal,
    STATE(113), 1,
      sym_key_value_item,
    STATE(147), 1,
      sym_expression,
    ACTIONS(128), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1464] = 14,
    ACTIONS(142), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(144), 1,
      anon_sym_0o,
    ACTIONS(146), 1,
      anon_sym_0x,
    ACTIONS(148), 1,
      anon_sym_SQUOTE,
    ACTIONS(150), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(154), 1,
      anon_sym_LBRACK,
    ACTIONS(156), 1,
      anon_sym_LBRACE,
    STATE(72), 1,
      sym_condition,
    STATE(91), 1,
      sym_literal,
    STATE(111), 1,
      sym_expression,
    ACTIONS(152), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(94), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(93), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(92), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1515] = 13,
    ACTIONS(118), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(120), 1,
      anon_sym_0o,
    ACTIONS(122), 1,
      anon_sym_0x,
    ACTIONS(124), 1,
      anon_sym_SQUOTE,
    ACTIONS(126), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(130), 1,
      anon_sym_LBRACK,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_literal,
    STATE(89), 1,
      sym_expression,
    ACTIONS(128), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1563] = 13,
    ACTIONS(118), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(120), 1,
      anon_sym_0o,
    ACTIONS(122), 1,
      anon_sym_0x,
    ACTIONS(124), 1,
      anon_sym_SQUOTE,
    ACTIONS(126), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(130), 1,
      anon_sym_LBRACK,
    ACTIONS(132), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_literal,
    STATE(112), 1,
      sym_expression,
    ACTIONS(128), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1611] = 2,
    ACTIONS(164), 2,
      sym__DECIMAL_NUMBER,
      anon_sym_SQUOTE,
    ACTIONS(162), 15,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_endif,
      anon_sym_foreach,
      anon_sym_endforeach,
      anon_sym_break,
      anon_sym_continue,
      anon_sym_0o,
      anon_sym_0x,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [1633] = 2,
    ACTIONS(168), 2,
      sym__DECIMAL_NUMBER,
      anon_sym_SQUOTE,
    ACTIONS(166), 12,
      anon_sym_if,
      anon_sym_foreach,
      anon_sym_endforeach,
      anon_sym_break,
      anon_sym_continue,
      anon_sym_0o,
      anon_sym_0x,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [1652] = 2,
    ACTIONS(164), 2,
      sym__DECIMAL_NUMBER,
      anon_sym_SQUOTE,
    ACTIONS(162), 10,
      ts_builtin_sym_end,
      anon_sym_if,
      anon_sym_foreach,
      anon_sym_0o,
      anon_sym_0x,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
  [1669] = 4,
    ACTIONS(172), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(174), 1,
      aux_sym_string_multiline_token1,
    STATE(34), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(170), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1684] = 4,
    ACTIONS(174), 1,
      aux_sym_string_multiline_token1,
    ACTIONS(176), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    STATE(34), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(170), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1699] = 4,
    ACTIONS(181), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(183), 1,
      aux_sym_string_multiline_token1,
    STATE(34), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(178), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1714] = 4,
    ACTIONS(188), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(190), 1,
      aux_sym_string_multiline_token1,
    STATE(37), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(186), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1729] = 4,
    ACTIONS(194), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(196), 1,
      aux_sym_string_multiline_token1,
    STATE(33), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(192), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1744] = 4,
    ACTIONS(174), 1,
      aux_sym_string_multiline_token1,
    ACTIONS(198), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    STATE(34), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(170), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1759] = 4,
    ACTIONS(202), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(204), 1,
      aux_sym_string_multiline_token1,
    STATE(32), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(200), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1774] = 1,
    ACTIONS(206), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1781] = 1,
    ACTIONS(208), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1788] = 1,
    ACTIONS(210), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1795] = 1,
    ACTIONS(212), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1802] = 4,
    ACTIONS(214), 1,
      sym_escape_sequence,
    ACTIONS(216), 1,
      anon_sym_SQUOTE,
    ACTIONS(218), 1,
      aux_sym_string_simple_token1,
    STATE(54), 1,
      aux_sym_string_simple_repeat1,
  [1815] = 1,
    ACTIONS(220), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1822] = 1,
    ACTIONS(222), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1829] = 1,
    ACTIONS(224), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1836] = 4,
    ACTIONS(214), 1,
      sym_escape_sequence,
    ACTIONS(218), 1,
      aux_sym_string_simple_token1,
    ACTIONS(226), 1,
      anon_sym_SQUOTE,
    STATE(54), 1,
      aux_sym_string_simple_repeat1,
  [1849] = 4,
    ACTIONS(228), 1,
      sym_escape_sequence,
    ACTIONS(230), 1,
      anon_sym_SQUOTE,
    ACTIONS(232), 1,
      aux_sym_string_simple_token1,
    STATE(47), 1,
      aux_sym_string_simple_repeat1,
  [1862] = 1,
    ACTIONS(234), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1869] = 1,
    ACTIONS(236), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1876] = 1,
    ACTIONS(238), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1883] = 1,
    ACTIONS(240), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1890] = 4,
    ACTIONS(242), 1,
      sym_escape_sequence,
    ACTIONS(244), 1,
      anon_sym_SQUOTE,
    ACTIONS(246), 1,
      aux_sym_string_simple_token1,
    STATE(43), 1,
      aux_sym_string_simple_repeat1,
  [1903] = 4,
    ACTIONS(248), 1,
      sym_escape_sequence,
    ACTIONS(251), 1,
      anon_sym_SQUOTE,
    ACTIONS(253), 1,
      aux_sym_string_simple_token1,
    STATE(54), 1,
      aux_sym_string_simple_repeat1,
  [1916] = 1,
    ACTIONS(256), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1923] = 4,
    ACTIONS(214), 1,
      sym_escape_sequence,
    ACTIONS(218), 1,
      aux_sym_string_simple_token1,
    ACTIONS(258), 1,
      anon_sym_SQUOTE,
    STATE(54), 1,
      aux_sym_string_simple_repeat1,
  [1936] = 1,
    ACTIONS(260), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1943] = 3,
    ACTIONS(262), 1,
      anon_sym_elif,
    STATE(58), 1,
      aux_sym_selection_statement_repeat1,
    ACTIONS(265), 2,
      anon_sym_else,
      anon_sym_endif,
  [1954] = 4,
    ACTIONS(23), 1,
      anon_sym_elif,
    ACTIONS(116), 1,
      anon_sym_endif,
    ACTIONS(267), 1,
      anon_sym_else,
    STATE(58), 1,
      aux_sym_selection_statement_repeat1,
  [1967] = 1,
    ACTIONS(269), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1974] = 4,
    ACTIONS(23), 1,
      anon_sym_elif,
    ACTIONS(70), 1,
      anon_sym_else,
    ACTIONS(72), 1,
      anon_sym_endif,
    STATE(58), 1,
      aux_sym_selection_statement_repeat1,
  [1987] = 1,
    ACTIONS(271), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1994] = 4,
    ACTIONS(273), 1,
      sym_escape_sequence,
    ACTIONS(275), 1,
      anon_sym_SQUOTE,
    ACTIONS(277), 1,
      aux_sym_string_simple_token1,
    STATE(56), 1,
      aux_sym_string_simple_repeat1,
  [2007] = 1,
    ACTIONS(279), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [2014] = 1,
    ACTIONS(281), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [2021] = 1,
    ACTIONS(283), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [2028] = 3,
    ACTIONS(285), 1,
      anon_sym_COLON,
    ACTIONS(287), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym_identifier_list_repeat1,
  [2038] = 3,
    ACTIONS(289), 1,
      anon_sym_COMMA,
    ACTIONS(292), 1,
      anon_sym_RBRACK,
    STATE(68), 1,
      aux_sym_array_literal_repeat1,
  [2048] = 3,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    ACTIONS(296), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      aux_sym_dictionary_literal_repeat1,
  [2058] = 3,
    ACTIONS(298), 1,
      anon_sym_COLON,
    ACTIONS(300), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym_identifier_list_repeat1,
  [2068] = 3,
    ACTIONS(303), 1,
      anon_sym_COMMA,
    ACTIONS(306), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      aux_sym_dictionary_literal_repeat1,
  [2078] = 2,
    STATE(9), 1,
      sym__NEWLINE,
    ACTIONS(308), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2086] = 2,
    STATE(5), 1,
      sym__NEWLINE,
    ACTIONS(310), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2094] = 2,
    STATE(2), 1,
      sym__NEWLINE,
    ACTIONS(312), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2102] = 3,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    ACTIONS(314), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      aux_sym_dictionary_literal_repeat1,
  [2112] = 2,
    STATE(30), 1,
      sym__NEWLINE,
    ACTIONS(316), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2120] = 3,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(320), 1,
      anon_sym_RBRACK,
    STATE(68), 1,
      aux_sym_array_literal_repeat1,
  [2130] = 3,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(322), 1,
      anon_sym_RBRACK,
    STATE(81), 1,
      aux_sym_array_literal_repeat1,
  [2140] = 3,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    ACTIONS(324), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      aux_sym_dictionary_literal_repeat1,
  [2150] = 3,
    ACTIONS(326), 1,
      sym__IDENTIFIER,
    STATE(84), 1,
      sym_id_expression,
    STATE(125), 1,
      sym_identifier_list,
  [2160] = 3,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(328), 1,
      anon_sym_RBRACK,
    STATE(68), 1,
      aux_sym_array_literal_repeat1,
  [2170] = 3,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    ACTIONS(330), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      aux_sym_dictionary_literal_repeat1,
  [2180] = 3,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    ACTIONS(332), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      aux_sym_dictionary_literal_repeat1,
  [2190] = 3,
    ACTIONS(287), 1,
      anon_sym_COMMA,
    ACTIONS(334), 1,
      anon_sym_COLON,
    STATE(67), 1,
      aux_sym_identifier_list_repeat1,
  [2200] = 3,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(336), 1,
      anon_sym_RBRACK,
    STATE(77), 1,
      aux_sym_array_literal_repeat1,
  [2210] = 3,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(338), 1,
      anon_sym_RBRACK,
    STATE(88), 1,
      aux_sym_array_literal_repeat1,
  [2220] = 3,
    ACTIONS(294), 1,
      anon_sym_COMMA,
    ACTIONS(340), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_dictionary_literal_repeat1,
  [2230] = 3,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(342), 1,
      anon_sym_RBRACK,
    STATE(68), 1,
      aux_sym_array_literal_repeat1,
  [2240] = 1,
    ACTIONS(344), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2245] = 1,
    ACTIONS(346), 2,
      anon_sym_COLON,
      anon_sym_COMMA,
  [2250] = 1,
    ACTIONS(348), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2255] = 1,
    ACTIONS(350), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2260] = 1,
    ACTIONS(352), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2265] = 1,
    ACTIONS(354), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2270] = 2,
    ACTIONS(356), 1,
      sym__IDENTIFIER,
    STATE(73), 1,
      sym_id_expression,
  [2277] = 1,
    ACTIONS(358), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2282] = 1,
    ACTIONS(360), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2287] = 1,
    ACTIONS(362), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2292] = 1,
    ACTIONS(364), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2297] = 1,
    ACTIONS(366), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2302] = 1,
    ACTIONS(368), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2307] = 2,
    ACTIONS(326), 1,
      sym__IDENTIFIER,
    STATE(103), 1,
      sym_id_expression,
  [2314] = 1,
    ACTIONS(298), 2,
      anon_sym_COLON,
      anon_sym_COMMA,
  [2319] = 1,
    ACTIONS(370), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2324] = 1,
    ACTIONS(372), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2329] = 1,
    ACTIONS(374), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2334] = 1,
    ACTIONS(376), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2339] = 1,
    ACTIONS(378), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2344] = 1,
    ACTIONS(380), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2349] = 1,
    ACTIONS(382), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2354] = 1,
    ACTIONS(384), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2359] = 1,
    ACTIONS(292), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2364] = 1,
    ACTIONS(306), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2369] = 1,
    ACTIONS(386), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2374] = 1,
    ACTIONS(388), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2379] = 1,
    ACTIONS(390), 1,
      anon_sym_LF,
  [2383] = 1,
    ACTIONS(240), 1,
      anon_sym_LF,
  [2387] = 1,
    ACTIONS(392), 1,
      ts_builtin_sym_end,
  [2391] = 1,
    ACTIONS(234), 1,
      anon_sym_LF,
  [2395] = 1,
    ACTIONS(394), 1,
      sym__HEX_NUMBER,
  [2399] = 1,
    ACTIONS(396), 1,
      anon_sym_LF,
  [2403] = 1,
    ACTIONS(212), 1,
      anon_sym_LF,
  [2407] = 1,
    ACTIONS(398), 1,
      anon_sym_LF,
  [2411] = 1,
    ACTIONS(281), 1,
      anon_sym_LF,
  [2415] = 1,
    ACTIONS(400), 1,
      anon_sym_COLON,
  [2419] = 1,
    ACTIONS(206), 1,
      anon_sym_LF,
  [2423] = 1,
    ACTIONS(283), 1,
      anon_sym_LF,
  [2427] = 1,
    ACTIONS(402), 1,
      sym__OCTAL_NUMBER,
  [2431] = 1,
    ACTIONS(404), 1,
      sym__HEX_NUMBER,
  [2435] = 1,
    ACTIONS(406), 1,
      anon_sym_LF,
  [2439] = 1,
    ACTIONS(210), 1,
      anon_sym_LF,
  [2443] = 1,
    ACTIONS(408), 1,
      anon_sym_LF,
  [2447] = 1,
    ACTIONS(410), 1,
      anon_sym_LF,
  [2451] = 1,
    ACTIONS(412), 1,
      anon_sym_LF,
  [2455] = 1,
    ACTIONS(414), 1,
      anon_sym_LF,
  [2459] = 1,
    ACTIONS(224), 1,
      anon_sym_LF,
  [2463] = 1,
    ACTIONS(279), 1,
      anon_sym_LF,
  [2467] = 1,
    ACTIONS(271), 1,
      anon_sym_LF,
  [2471] = 1,
    ACTIONS(269), 1,
      anon_sym_LF,
  [2475] = 1,
    ACTIONS(236), 1,
      anon_sym_LF,
  [2479] = 1,
    ACTIONS(416), 1,
      sym__OCTAL_NUMBER,
  [2483] = 1,
    ACTIONS(418), 1,
      sym__HEX_NUMBER,
  [2487] = 1,
    ACTIONS(420), 1,
      sym__OCTAL_NUMBER,
  [2491] = 1,
    ACTIONS(222), 1,
      anon_sym_LF,
  [2495] = 1,
    ACTIONS(220), 1,
      anon_sym_LF,
  [2499] = 1,
    ACTIONS(422), 1,
      anon_sym_LF,
  [2503] = 1,
    ACTIONS(424), 1,
      anon_sym_COLON,
  [2507] = 1,
    ACTIONS(426), 1,
      ts_builtin_sym_end,
  [2511] = 1,
    ACTIONS(260), 1,
      anon_sym_LF,
  [2515] = 1,
    ACTIONS(256), 1,
      anon_sym_LF,
  [2519] = 1,
    ACTIONS(208), 1,
      anon_sym_LF,
  [2523] = 1,
    ACTIONS(238), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 72,
  [SMALL_STATE(4)] = 140,
  [SMALL_STATE(5)] = 208,
  [SMALL_STATE(6)] = 276,
  [SMALL_STATE(7)] = 348,
  [SMALL_STATE(8)] = 413,
  [SMALL_STATE(9)] = 478,
  [SMALL_STATE(10)] = 543,
  [SMALL_STATE(11)] = 606,
  [SMALL_STATE(12)] = 669,
  [SMALL_STATE(13)] = 732,
  [SMALL_STATE(14)] = 795,
  [SMALL_STATE(15)] = 858,
  [SMALL_STATE(16)] = 921,
  [SMALL_STATE(17)] = 984,
  [SMALL_STATE(18)] = 1047,
  [SMALL_STATE(19)] = 1101,
  [SMALL_STATE(20)] = 1155,
  [SMALL_STATE(21)] = 1209,
  [SMALL_STATE(22)] = 1260,
  [SMALL_STATE(23)] = 1311,
  [SMALL_STATE(24)] = 1362,
  [SMALL_STATE(25)] = 1413,
  [SMALL_STATE(26)] = 1464,
  [SMALL_STATE(27)] = 1515,
  [SMALL_STATE(28)] = 1563,
  [SMALL_STATE(29)] = 1611,
  [SMALL_STATE(30)] = 1633,
  [SMALL_STATE(31)] = 1652,
  [SMALL_STATE(32)] = 1669,
  [SMALL_STATE(33)] = 1684,
  [SMALL_STATE(34)] = 1699,
  [SMALL_STATE(35)] = 1714,
  [SMALL_STATE(36)] = 1729,
  [SMALL_STATE(37)] = 1744,
  [SMALL_STATE(38)] = 1759,
  [SMALL_STATE(39)] = 1774,
  [SMALL_STATE(40)] = 1781,
  [SMALL_STATE(41)] = 1788,
  [SMALL_STATE(42)] = 1795,
  [SMALL_STATE(43)] = 1802,
  [SMALL_STATE(44)] = 1815,
  [SMALL_STATE(45)] = 1822,
  [SMALL_STATE(46)] = 1829,
  [SMALL_STATE(47)] = 1836,
  [SMALL_STATE(48)] = 1849,
  [SMALL_STATE(49)] = 1862,
  [SMALL_STATE(50)] = 1869,
  [SMALL_STATE(51)] = 1876,
  [SMALL_STATE(52)] = 1883,
  [SMALL_STATE(53)] = 1890,
  [SMALL_STATE(54)] = 1903,
  [SMALL_STATE(55)] = 1916,
  [SMALL_STATE(56)] = 1923,
  [SMALL_STATE(57)] = 1936,
  [SMALL_STATE(58)] = 1943,
  [SMALL_STATE(59)] = 1954,
  [SMALL_STATE(60)] = 1967,
  [SMALL_STATE(61)] = 1974,
  [SMALL_STATE(62)] = 1987,
  [SMALL_STATE(63)] = 1994,
  [SMALL_STATE(64)] = 2007,
  [SMALL_STATE(65)] = 2014,
  [SMALL_STATE(66)] = 2021,
  [SMALL_STATE(67)] = 2028,
  [SMALL_STATE(68)] = 2038,
  [SMALL_STATE(69)] = 2048,
  [SMALL_STATE(70)] = 2058,
  [SMALL_STATE(71)] = 2068,
  [SMALL_STATE(72)] = 2078,
  [SMALL_STATE(73)] = 2086,
  [SMALL_STATE(74)] = 2094,
  [SMALL_STATE(75)] = 2102,
  [SMALL_STATE(76)] = 2112,
  [SMALL_STATE(77)] = 2120,
  [SMALL_STATE(78)] = 2130,
  [SMALL_STATE(79)] = 2140,
  [SMALL_STATE(80)] = 2150,
  [SMALL_STATE(81)] = 2160,
  [SMALL_STATE(82)] = 2170,
  [SMALL_STATE(83)] = 2180,
  [SMALL_STATE(84)] = 2190,
  [SMALL_STATE(85)] = 2200,
  [SMALL_STATE(86)] = 2210,
  [SMALL_STATE(87)] = 2220,
  [SMALL_STATE(88)] = 2230,
  [SMALL_STATE(89)] = 2240,
  [SMALL_STATE(90)] = 2245,
  [SMALL_STATE(91)] = 2250,
  [SMALL_STATE(92)] = 2255,
  [SMALL_STATE(93)] = 2260,
  [SMALL_STATE(94)] = 2265,
  [SMALL_STATE(95)] = 2270,
  [SMALL_STATE(96)] = 2277,
  [SMALL_STATE(97)] = 2282,
  [SMALL_STATE(98)] = 2287,
  [SMALL_STATE(99)] = 2292,
  [SMALL_STATE(100)] = 2297,
  [SMALL_STATE(101)] = 2302,
  [SMALL_STATE(102)] = 2307,
  [SMALL_STATE(103)] = 2314,
  [SMALL_STATE(104)] = 2319,
  [SMALL_STATE(105)] = 2324,
  [SMALL_STATE(106)] = 2329,
  [SMALL_STATE(107)] = 2334,
  [SMALL_STATE(108)] = 2339,
  [SMALL_STATE(109)] = 2344,
  [SMALL_STATE(110)] = 2349,
  [SMALL_STATE(111)] = 2354,
  [SMALL_STATE(112)] = 2359,
  [SMALL_STATE(113)] = 2364,
  [SMALL_STATE(114)] = 2369,
  [SMALL_STATE(115)] = 2374,
  [SMALL_STATE(116)] = 2379,
  [SMALL_STATE(117)] = 2383,
  [SMALL_STATE(118)] = 2387,
  [SMALL_STATE(119)] = 2391,
  [SMALL_STATE(120)] = 2395,
  [SMALL_STATE(121)] = 2399,
  [SMALL_STATE(122)] = 2403,
  [SMALL_STATE(123)] = 2407,
  [SMALL_STATE(124)] = 2411,
  [SMALL_STATE(125)] = 2415,
  [SMALL_STATE(126)] = 2419,
  [SMALL_STATE(127)] = 2423,
  [SMALL_STATE(128)] = 2427,
  [SMALL_STATE(129)] = 2431,
  [SMALL_STATE(130)] = 2435,
  [SMALL_STATE(131)] = 2439,
  [SMALL_STATE(132)] = 2443,
  [SMALL_STATE(133)] = 2447,
  [SMALL_STATE(134)] = 2451,
  [SMALL_STATE(135)] = 2455,
  [SMALL_STATE(136)] = 2459,
  [SMALL_STATE(137)] = 2463,
  [SMALL_STATE(138)] = 2467,
  [SMALL_STATE(139)] = 2471,
  [SMALL_STATE(140)] = 2475,
  [SMALL_STATE(141)] = 2479,
  [SMALL_STATE(142)] = 2483,
  [SMALL_STATE(143)] = 2487,
  [SMALL_STATE(144)] = 2491,
  [SMALL_STATE(145)] = 2495,
  [SMALL_STATE(146)] = 2499,
  [SMALL_STATE(147)] = 2503,
  [SMALL_STATE(148)] = 2507,
  [SMALL_STATE(149)] = 2511,
  [SMALL_STATE(150)] = 2515,
  [SMALL_STATE(151)] = 2519,
  [SMALL_STATE(152)] = 2523,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(22),
  [32] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(80),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(76),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(131),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(143),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(120),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(53),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(36),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(122),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(24),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(18),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(22),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(80),
  [82] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(131),
  [85] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(143),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(120),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(53),
  [94] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(36),
  [97] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(122),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(24),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(18),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selection_statement_repeat1, 4),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selection_statement_repeat1, 3),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_build_definition, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [142] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [148] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [150] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump_statement, 2),
  [168] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump_statement, 2),
  [170] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [172] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [176] = {.entry = {.count = 1, .reusable = false}}, SHIFT(138),
  [178] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_multiline_repeat1, 2), SHIFT_REPEAT(34),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_multiline_repeat1, 2),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_multiline_repeat1, 2), SHIFT_REPEAT(34),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [188] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(151),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [202] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_octal_literal, 2),
  [208] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_multiline, 2),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decimal_literal, 1),
  [212] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [216] = {.entry = {.count = 1, .reusable = false}}, SHIFT(139),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer_literal, 1),
  [226] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [228] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 1),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hex_literal, 2),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_simple, 2),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary_literal, 3),
  [242] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [244] = {.entry = {.count = 1, .reusable = false}}, SHIFT(152),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [248] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_simple_repeat1, 2), SHIFT_REPEAT(54),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_simple_repeat1, 2),
  [253] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_simple_repeat1, 2), SHIFT_REPEAT(54),
  [256] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 2),
  [258] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [260] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary_literal, 2),
  [262] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_selection_statement_repeat1, 2), SHIFT_REPEAT(26),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selection_statement_repeat1, 2),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_simple, 3),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_multiline, 3),
  [273] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [275] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [279] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 3),
  [281] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary_literal, 4),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 4),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_list, 2),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [289] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2), SHIFT_REPEAT(28),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identifier_list_repeat1, 2),
  [300] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identifier_list_repeat1, 2), SHIFT_REPEAT(102),
  [303] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dictionary_literal_repeat1, 2), SHIFT_REPEAT(25),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dictionary_literal_repeat1, 2),
  [308] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [310] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [312] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [316] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_list, 1),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [344] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value_item, 3, .production_id = 1),
  [346] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id_expression, 1),
  [348] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [350] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1),
  [352] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer_literal, 1),
  [354] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 1),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [358] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_octal_literal, 2),
  [360] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hex_literal, 2),
  [362] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_simple, 2),
  [364] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_multiline, 2),
  [366] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 2),
  [368] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary_literal, 2),
  [370] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_simple, 3),
  [372] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_multiline, 3),
  [374] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 3),
  [376] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary_literal, 3),
  [378] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 4),
  [380] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary_literal, 4),
  [382] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decimal_literal, 1),
  [384] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_condition, 1),
  [386] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1),
  [388] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_id_expression, 1),
  [390] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_iteration_statement, 6),
  [392] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [394] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [396] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 6),
  [398] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 5),
  [400] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [402] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [404] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [406] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_iteration_statement, 7),
  [408] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 8),
  [410] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 4),
  [412] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [414] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 7),
  [416] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [418] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [420] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [422] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [424] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [426] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_meson(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
