#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 13
#define STATE_COUNT 153
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 64
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 2

enum {
  anon_sym_LF = 1,
  anon_sym_if = 2,
  anon_sym_elif = 3,
  anon_sym_else = 4,
  anon_sym_endif = 5,
  anon_sym_foreach = 6,
  anon_sym_COLON = 7,
  anon_sym_endforeach = 8,
  anon_sym_break = 9,
  anon_sym_continue = 10,
  sym__DECIMAL_NUMBER = 11,
  anon_sym_0o = 12,
  sym__OCTAL_NUMBER = 13,
  anon_sym_0x = 14,
  sym__HEX_NUMBER = 15,
  sym_escape_sequence = 16,
  anon_sym_SQUOTE = 17,
  aux_sym_string_simple_token1 = 18,
  anon_sym_SQUOTE_SQUOTE_SQUOTE = 19,
  aux_sym_string_multiline_token1 = 20,
  anon_sym_SQUOTE_SQUOTE = 21,
  anon_sym_true = 22,
  anon_sym_false = 23,
  anon_sym_LBRACK = 24,
  anon_sym_COMMA = 25,
  anon_sym_RBRACK = 26,
  anon_sym_LF2 = 27,
  anon_sym_CR_LF = 28,
  anon_sym_LBRACE = 29,
  anon_sym_RBRACE = 30,
  sym__IDENTIFIER = 31,
  sym_comment = 32,
  sym_source_file = 33,
  sym_build_definition = 34,
  sym_statement = 35,
  sym_selection_statement = 36,
  sym_iteration_statement = 37,
  sym_jump_statement = 38,
  sym_condition = 39,
  sym_expression = 40,
  sym_literal = 41,
  sym_integer_literal = 42,
  sym_decimal_literal = 43,
  sym_octal_literal = 44,
  sym_hex_literal = 45,
  sym_string_literal = 46,
  sym_string_simple = 47,
  sym_string_multiline = 48,
  sym_boolean_literal = 49,
  sym_array_literal = 50,
  sym__NEWLINE = 51,
  sym_dictionary_literal = 52,
  sym_key_value_item = 53,
  sym_identifier_list = 54,
  sym_id_expression = 55,
  aux_sym_build_definition_repeat1 = 56,
  aux_sym_selection_statement_repeat1 = 57,
  aux_sym_iteration_statement_repeat1 = 58,
  aux_sym_string_simple_repeat1 = 59,
  aux_sym_string_multiline_repeat1 = 60,
  aux_sym_array_literal_repeat1 = 61,
  aux_sym_dictionary_literal_repeat1 = 62,
  aux_sym_identifier_list_repeat1 = 63,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LF] = "\n",
  [anon_sym_if] = "if",
  [anon_sym_elif] = "elif",
  [anon_sym_else] = "else",
  [anon_sym_endif] = "endif",
  [anon_sym_foreach] = "foreach",
  [anon_sym_COLON] = ":",
  [anon_sym_endforeach] = "endforeach",
  [anon_sym_break] = "break",
  [anon_sym_continue] = "continue",
  [sym__DECIMAL_NUMBER] = "_DECIMAL_NUMBER",
  [anon_sym_0o] = "0o",
  [sym__OCTAL_NUMBER] = "_OCTAL_NUMBER",
  [anon_sym_0x] = "0x",
  [sym__HEX_NUMBER] = "_HEX_NUMBER",
  [sym_escape_sequence] = "escape_sequence",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_simple_token1] = "string_simple_token1",
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = "'''",
  [aux_sym_string_multiline_token1] = "string_multiline_token1",
  [anon_sym_SQUOTE_SQUOTE] = "''",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_LBRACK] = "[",
  [anon_sym_COMMA] = ",",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LF2] = "\n",
  [anon_sym_CR_LF] = "\r\n",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [sym__IDENTIFIER] = "_IDENTIFIER",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_build_definition] = "build_definition",
  [sym_statement] = "statement",
  [sym_selection_statement] = "selection_statement",
  [sym_iteration_statement] = "iteration_statement",
  [sym_jump_statement] = "jump_statement",
  [sym_condition] = "condition",
  [sym_expression] = "expression",
  [sym_literal] = "literal",
  [sym_integer_literal] = "integer_literal",
  [sym_decimal_literal] = "decimal_literal",
  [sym_octal_literal] = "octal_literal",
  [sym_hex_literal] = "hex_literal",
  [sym_string_literal] = "string_literal",
  [sym_string_simple] = "string_simple",
  [sym_string_multiline] = "string_multiline",
  [sym_boolean_literal] = "boolean_literal",
  [sym_array_literal] = "array_literal",
  [sym__NEWLINE] = "_NEWLINE",
  [sym_dictionary_literal] = "dictionary_literal",
  [sym_key_value_item] = "key_value_item",
  [sym_identifier_list] = "identifier_list",
  [sym_id_expression] = "id_expression",
  [aux_sym_build_definition_repeat1] = "build_definition_repeat1",
  [aux_sym_selection_statement_repeat1] = "selection_statement_repeat1",
  [aux_sym_iteration_statement_repeat1] = "iteration_statement_repeat1",
  [aux_sym_string_simple_repeat1] = "string_simple_repeat1",
  [aux_sym_string_multiline_repeat1] = "string_multiline_repeat1",
  [aux_sym_array_literal_repeat1] = "array_literal_repeat1",
  [aux_sym_dictionary_literal_repeat1] = "dictionary_literal_repeat1",
  [aux_sym_identifier_list_repeat1] = "identifier_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_elif] = anon_sym_elif,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_endif] = anon_sym_endif,
  [anon_sym_foreach] = anon_sym_foreach,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_endforeach] = anon_sym_endforeach,
  [anon_sym_break] = anon_sym_break,
  [anon_sym_continue] = anon_sym_continue,
  [sym__DECIMAL_NUMBER] = sym__DECIMAL_NUMBER,
  [anon_sym_0o] = anon_sym_0o,
  [sym__OCTAL_NUMBER] = sym__OCTAL_NUMBER,
  [anon_sym_0x] = anon_sym_0x,
  [sym__HEX_NUMBER] = sym__HEX_NUMBER,
  [sym_escape_sequence] = sym_escape_sequence,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_simple_token1] = aux_sym_string_simple_token1,
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = anon_sym_SQUOTE_SQUOTE_SQUOTE,
  [aux_sym_string_multiline_token1] = aux_sym_string_multiline_token1,
  [anon_sym_SQUOTE_SQUOTE] = anon_sym_SQUOTE_SQUOTE,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LF2] = anon_sym_LF,
  [anon_sym_CR_LF] = anon_sym_CR_LF,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [sym__IDENTIFIER] = sym__IDENTIFIER,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_build_definition] = sym_build_definition,
  [sym_statement] = sym_statement,
  [sym_selection_statement] = sym_selection_statement,
  [sym_iteration_statement] = sym_iteration_statement,
  [sym_jump_statement] = sym_jump_statement,
  [sym_condition] = sym_condition,
  [sym_expression] = sym_expression,
  [sym_literal] = sym_literal,
  [sym_integer_literal] = sym_integer_literal,
  [sym_decimal_literal] = sym_decimal_literal,
  [sym_octal_literal] = sym_octal_literal,
  [sym_hex_literal] = sym_hex_literal,
  [sym_string_literal] = sym_string_literal,
  [sym_string_simple] = sym_string_simple,
  [sym_string_multiline] = sym_string_multiline,
  [sym_boolean_literal] = sym_boolean_literal,
  [sym_array_literal] = sym_array_literal,
  [sym__NEWLINE] = sym__NEWLINE,
  [sym_dictionary_literal] = sym_dictionary_literal,
  [sym_key_value_item] = sym_key_value_item,
  [sym_identifier_list] = sym_identifier_list,
  [sym_id_expression] = sym_id_expression,
  [aux_sym_build_definition_repeat1] = aux_sym_build_definition_repeat1,
  [aux_sym_selection_statement_repeat1] = aux_sym_selection_statement_repeat1,
  [aux_sym_iteration_statement_repeat1] = aux_sym_iteration_statement_repeat1,
  [aux_sym_string_simple_repeat1] = aux_sym_string_simple_repeat1,
  [aux_sym_string_multiline_repeat1] = aux_sym_string_multiline_repeat1,
  [aux_sym_array_literal_repeat1] = aux_sym_array_literal_repeat1,
  [aux_sym_dictionary_literal_repeat1] = aux_sym_dictionary_literal_repeat1,
  [aux_sym_identifier_list_repeat1] = aux_sym_identifier_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_elif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endif] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_foreach] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endforeach] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_break] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_continue] = {
    .visible = true,
    .named = false,
  },
  [sym__DECIMAL_NUMBER] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_0o] = {
    .visible = true,
    .named = false,
  },
  [sym__OCTAL_NUMBER] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_0x] = {
    .visible = true,
    .named = false,
  },
  [sym__HEX_NUMBER] = {
    .visible = false,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_simple_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE_SQUOTE_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_multiline_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF2] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_CR_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [sym__IDENTIFIER] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_build_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_selection_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_iteration_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_jump_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_condition] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_integer_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_decimal_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_octal_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_simple] = {
    .visible = true,
    .named = true,
  },
  [sym_string_multiline] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_array_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__NEWLINE] = {
    .visible = false,
    .named = true,
  },
  [sym_dictionary_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_key_value_item] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier_list] = {
    .visible = true,
    .named = true,
  },
  [sym_id_expression] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_build_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_selection_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_iteration_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_simple_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_multiline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dictionary_literal_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_identifier_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_key = 1,
  field_value = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(57);
      if (lookahead == '#') ADVANCE(1);
      if (lookahead == '\'') ADVANCE(86);
      if (lookahead == ',') ADVANCE(97);
      if (lookahead == '0') ADVANCE(68);
      if (lookahead == ':') ADVANCE(64);
      if (lookahead == '[') ADVANCE(96);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == ']') ADVANCE(98);
      if (lookahead == 'b') ADVANCE(80);
      if (lookahead == 'c') ADVANCE(79);
      if (lookahead == 'e') ADVANCE(77);
      if (lookahead == 'f') ADVANCE(76);
      if (lookahead == 'i') ADVANCE(23);
      if (lookahead == 't') ADVANCE(39);
      if (lookahead == '{') ADVANCE(100);
      if (lookahead == '}') ADVANCE(101);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(71);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('1' <= lookahead && lookahead <= '7')) ADVANCE(70);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'd')) ADVANCE(81);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(103);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\n') SKIP(7)
      if (lookahead == '\'') ADVANCE(85);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0) ADVANCE(89);
      END_STATE();
    case 3:
      if (lookahead == '\n') ADVANCE(99);
      if (lookahead == '\r') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(3)
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(58);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(86);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0) ADVANCE(92);
      END_STATE();
    case 6:
      if (lookahead == '\'') ADVANCE(90);
      END_STATE();
    case 7:
      if (lookahead == '\'') ADVANCE(85);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(7)
      END_STATE();
    case 8:
      if (lookahead == 'U') ADVANCE(55);
      if (lookahead == 'u') ADVANCE(51);
      if (lookahead == 'x') ADVANCE(49);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(84);
      if (lookahead != 0) ADVANCE(82);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(31);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 11:
      if (lookahead == 'a') ADVANCE(33);
      if (lookahead == 'o') ADVANCE(40);
      END_STATE();
    case 12:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 13:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 14:
      if (lookahead == 'c') ADVANCE(28);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(25);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(9);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(61);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(94);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(95);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(10);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(12);
      END_STATE();
    case 23:
      if (lookahead == 'f') ADVANCE(59);
      END_STATE();
    case 24:
      if (lookahead == 'f') ADVANCE(60);
      END_STATE();
    case 25:
      if (lookahead == 'f') ADVANCE(37);
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 26:
      if (lookahead == 'f') ADVANCE(62);
      END_STATE();
    case 27:
      if (lookahead == 'h') ADVANCE(63);
      END_STATE();
    case 28:
      if (lookahead == 'h') ADVANCE(65);
      END_STATE();
    case 29:
      if (lookahead == 'i') ADVANCE(24);
      if (lookahead == 's') ADVANCE(17);
      END_STATE();
    case 30:
      if (lookahead == 'i') ADVANCE(35);
      END_STATE();
    case 31:
      if (lookahead == 'k') ADVANCE(66);
      END_STATE();
    case 32:
      if (lookahead == 'l') ADVANCE(29);
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 33:
      if (lookahead == 'l') ADVANCE(42);
      END_STATE();
    case 34:
      if (lookahead == 'n') ADVANCE(43);
      END_STATE();
    case 35:
      if (lookahead == 'n') ADVANCE(45);
      END_STATE();
    case 36:
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 37:
      if (lookahead == 'o') ADVANCE(41);
      END_STATE();
    case 38:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 39:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 40:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(22);
      END_STATE();
    case 42:
      if (lookahead == 's') ADVANCE(19);
      END_STATE();
    case 43:
      if (lookahead == 't') ADVANCE(30);
      END_STATE();
    case 44:
      if (lookahead == 'u') ADVANCE(18);
      END_STATE();
    case 45:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 46:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(46)
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(74);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 47:
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(47)
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(81);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(82);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(48);
      END_STATE();
    case 50:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(49);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(50);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(51);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(53);
      END_STATE();
    case 55:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(54);
      END_STATE();
    case 56:
      if (eof) ADVANCE(57);
      if (lookahead == '#') ADVANCE(1);
      if (lookahead == '\'') ADVANCE(87);
      if (lookahead == '0') ADVANCE(69);
      if (lookahead == '[') ADVANCE(96);
      if (lookahead == ']') ADVANCE(98);
      if (lookahead == 'b') ADVANCE(38);
      if (lookahead == 'c') ADVANCE(36);
      if (lookahead == 'e') ADVANCE(32);
      if (lookahead == 'f') ADVANCE(11);
      if (lookahead == 'i') ADVANCE(23);
      if (lookahead == 't') ADVANCE(39);
      if (lookahead == '{') ADVANCE(100);
      if (lookahead == '}') ADVANCE(101);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(56)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_elif);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_endif);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_foreach);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_endforeach);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_break);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_continue);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym__DECIMAL_NUMBER);
      if (lookahead == 'o') ADVANCE(73);
      if (lookahead == 'x') ADVANCE(75);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(70);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(81);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym__DECIMAL_NUMBER);
      if (lookahead == 'o') ADVANCE(73);
      if (lookahead == 'x') ADVANCE(75);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym__DECIMAL_NUMBER);
      if (lookahead == '8' ||
          lookahead == '9') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(70);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(81);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym__DECIMAL_NUMBER);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(71);
      if (('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(81);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym__DECIMAL_NUMBER);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(anon_sym_0o);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym__OCTAL_NUMBER);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_0x);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym__HEX_NUMBER);
      if (lookahead == 'a') ADVANCE(78);
      if (lookahead == 'o') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('b' <= lookahead && lookahead <= 'f')) ADVANCE(81);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym__HEX_NUMBER);
      if (lookahead == 'l') ADVANCE(29);
      if (lookahead == 'n') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(81);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym__HEX_NUMBER);
      if (lookahead == 'l') ADVANCE(42);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(81);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym__HEX_NUMBER);
      if (lookahead == 'o') ADVANCE(34);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(81);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym__HEX_NUMBER);
      if (lookahead == 'r') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(81);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym__HEX_NUMBER);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(82);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(83);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '\'') ADVANCE(93);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      if (lookahead == '\'') ADVANCE(6);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_string_simple_token1);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(89);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_string_simple_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(anon_sym_SQUOTE_SQUOTE_SQUOTE);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_string_multiline_token1);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(92);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_string_multiline_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(92);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_SQUOTE_SQUOTE);
      if (lookahead == '\'') ADVANCE(90);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_LF2);
      if (lookahead == '\n') ADVANCE(99);
      if (lookahead == '\r') ADVANCE(3);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym__IDENTIFIER);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(102);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 56},
  [2] = {.lex_state = 56},
  [3] = {.lex_state = 56},
  [4] = {.lex_state = 56},
  [5] = {.lex_state = 56},
  [6] = {.lex_state = 56},
  [7] = {.lex_state = 56},
  [8] = {.lex_state = 56},
  [9] = {.lex_state = 56},
  [10] = {.lex_state = 56},
  [11] = {.lex_state = 56},
  [12] = {.lex_state = 56},
  [13] = {.lex_state = 56},
  [14] = {.lex_state = 56},
  [15] = {.lex_state = 56},
  [16] = {.lex_state = 56},
  [17] = {.lex_state = 56},
  [18] = {.lex_state = 56},
  [19] = {.lex_state = 56},
  [20] = {.lex_state = 56},
  [21] = {.lex_state = 56},
  [22] = {.lex_state = 56},
  [23] = {.lex_state = 56},
  [24] = {.lex_state = 56},
  [25] = {.lex_state = 56},
  [26] = {.lex_state = 56},
  [27] = {.lex_state = 56},
  [28] = {.lex_state = 56},
  [29] = {.lex_state = 56},
  [30] = {.lex_state = 56},
  [31] = {.lex_state = 56},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 2},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 2},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 56},
  [59] = {.lex_state = 56},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 56},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 3},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 3},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 3},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 46},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 3},
  [92] = {.lex_state = 3},
  [93] = {.lex_state = 3},
  [94] = {.lex_state = 3},
  [95] = {.lex_state = 46},
  [96] = {.lex_state = 3},
  [97] = {.lex_state = 3},
  [98] = {.lex_state = 3},
  [99] = {.lex_state = 3},
  [100] = {.lex_state = 3},
  [101] = {.lex_state = 3},
  [102] = {.lex_state = 46},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 3},
  [105] = {.lex_state = 3},
  [106] = {.lex_state = 3},
  [107] = {.lex_state = 3},
  [108] = {.lex_state = 3},
  [109] = {.lex_state = 3},
  [110] = {.lex_state = 3},
  [111] = {.lex_state = 3},
  [112] = {.lex_state = 0},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 3},
  [115] = {.lex_state = 3},
  [116] = {.lex_state = 4},
  [117] = {.lex_state = 4},
  [118] = {.lex_state = 4},
  [119] = {.lex_state = 4},
  [120] = {.lex_state = 47},
  [121] = {.lex_state = 4},
  [122] = {.lex_state = 4},
  [123] = {.lex_state = 4},
  [124] = {.lex_state = 4},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 4},
  [127] = {.lex_state = 4},
  [128] = {.lex_state = 46},
  [129] = {.lex_state = 47},
  [130] = {.lex_state = 4},
  [131] = {.lex_state = 4},
  [132] = {.lex_state = 4},
  [133] = {.lex_state = 4},
  [134] = {.lex_state = 4},
  [135] = {.lex_state = 4},
  [136] = {.lex_state = 4},
  [137] = {.lex_state = 4},
  [138] = {.lex_state = 4},
  [139] = {.lex_state = 4},
  [140] = {.lex_state = 4},
  [141] = {.lex_state = 46},
  [142] = {.lex_state = 47},
  [143] = {.lex_state = 46},
  [144] = {.lex_state = 4},
  [145] = {.lex_state = 4},
  [146] = {.lex_state = 0},
  [147] = {.lex_state = 0},
  [148] = {.lex_state = 0},
  [149] = {.lex_state = 4},
  [150] = {.lex_state = 4},
  [151] = {.lex_state = 4},
  [152] = {.lex_state = 4},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_elif] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_endif] = ACTIONS(1),
    [anon_sym_foreach] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_endforeach] = ACTIONS(1),
    [anon_sym_break] = ACTIONS(1),
    [anon_sym_continue] = ACTIONS(1),
    [sym__DECIMAL_NUMBER] = ACTIONS(1),
    [anon_sym_0o] = ACTIONS(1),
    [sym__OCTAL_NUMBER] = ACTIONS(1),
    [anon_sym_0x] = ACTIONS(1),
    [sym__HEX_NUMBER] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE_SQUOTE] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(148),
    [sym_build_definition] = STATE(146),
    [sym_statement] = STATE(13),
    [sym_selection_statement] = STATE(118),
    [sym_iteration_statement] = STATE(118),
    [sym_expression] = STATE(118),
    [sym_literal] = STATE(145),
    [sym_integer_literal] = STATE(144),
    [sym_decimal_literal] = STATE(136),
    [sym_octal_literal] = STATE(136),
    [sym_hex_literal] = STATE(136),
    [sym_string_literal] = STATE(144),
    [sym_string_simple] = STATE(119),
    [sym_string_multiline] = STATE(119),
    [sym_boolean_literal] = STATE(144),
    [sym_array_literal] = STATE(144),
    [sym_dictionary_literal] = STATE(144),
    [aux_sym_build_definition_repeat1] = STATE(13),
    [anon_sym_if] = ACTIONS(3),
    [anon_sym_foreach] = ACTIONS(5),
    [sym__DECIMAL_NUMBER] = ACTIONS(7),
    [anon_sym_0o] = ACTIONS(9),
    [anon_sym_0x] = ACTIONS(11),
    [anon_sym_SQUOTE] = ACTIONS(13),
    [anon_sym_SQUOTE_SQUOTE_SQUOTE] = ACTIONS(15),
    [anon_sym_true] = ACTIONS(17),
    [anon_sym_false] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [anon_sym_LBRACE] = ACTIONS(21),
    [sym_comment] = ACTIONS(23),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 21,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_elif,
    ACTIONS(27), 1,
      anon_sym_else,
    ACTIONS(29), 1,
      anon_sym_endif,
    ACTIONS(31), 1,
      sym_comment,
    STATE(61), 1,
      aux_sym_selection_statement_repeat1,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(6), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [75] = 19,
    ACTIONS(33), 1,
      anon_sym_if,
    ACTIONS(36), 1,
      anon_sym_foreach,
    ACTIONS(39), 1,
      anon_sym_endforeach,
    ACTIONS(44), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(47), 1,
      anon_sym_0o,
    ACTIONS(50), 1,
      anon_sym_0x,
    ACTIONS(53), 1,
      anon_sym_SQUOTE,
    ACTIONS(56), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(62), 1,
      anon_sym_LBRACK,
    ACTIONS(65), 1,
      anon_sym_LBRACE,
    ACTIONS(68), 1,
      sym_comment,
    STATE(145), 1,
      sym_literal,
    ACTIONS(41), 2,
      anon_sym_break,
      anon_sym_continue,
    ACTIONS(59), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(3), 3,
      sym_statement,
      sym_jump_statement,
      aux_sym_iteration_statement_repeat1,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [146] = 19,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(71), 1,
      anon_sym_endforeach,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(73), 2,
      anon_sym_break,
      anon_sym_continue,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(3), 3,
      sym_statement,
      sym_jump_statement,
      aux_sym_iteration_statement_repeat1,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [217] = 19,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(75), 1,
      anon_sym_endforeach,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(73), 2,
      anon_sym_break,
      anon_sym_continue,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(4), 3,
      sym_statement,
      sym_jump_statement,
      aux_sym_iteration_statement_repeat1,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [288] = 21,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(25), 1,
      anon_sym_elif,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(77), 1,
      anon_sym_else,
    ACTIONS(79), 1,
      anon_sym_endif,
    STATE(59), 1,
      aux_sym_selection_statement_repeat1,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [363] = 18,
    ACTIONS(81), 1,
      anon_sym_if,
    ACTIONS(86), 1,
      anon_sym_foreach,
    ACTIONS(89), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(92), 1,
      anon_sym_0o,
    ACTIONS(95), 1,
      anon_sym_0x,
    ACTIONS(98), 1,
      anon_sym_SQUOTE,
    ACTIONS(101), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(113), 1,
      sym_comment,
    STATE(145), 1,
      sym_literal,
    ACTIONS(104), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    ACTIONS(84), 3,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_endif,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [431] = 18,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_comment,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    ACTIONS(116), 3,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_endif,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [499] = 18,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_comment,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(8), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    ACTIONS(118), 3,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_endif,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [567] = 18,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_endif,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [633] = 18,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(79), 1,
      anon_sym_endif,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(16), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [699] = 18,
    ACTIONS(81), 1,
      anon_sym_if,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
    ACTIONS(86), 1,
      anon_sym_foreach,
    ACTIONS(89), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(92), 1,
      anon_sym_0o,
    ACTIONS(95), 1,
      anon_sym_0x,
    ACTIONS(98), 1,
      anon_sym_SQUOTE,
    ACTIONS(101), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(107), 1,
      anon_sym_LBRACK,
    ACTIONS(110), 1,
      anon_sym_LBRACE,
    ACTIONS(122), 1,
      sym_comment,
    STATE(145), 1,
      sym_literal,
    ACTIONS(104), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(118), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [765] = 18,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(23), 1,
      sym_comment,
    ACTIONS(125), 1,
      ts_builtin_sym_end,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(12), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(118), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [831] = 18,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(120), 1,
      anon_sym_endif,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(15), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [897] = 18,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(127), 1,
      anon_sym_endif,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [963] = 18,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_endif,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(7), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1029] = 18,
    ACTIONS(3), 1,
      anon_sym_if,
    ACTIONS(5), 1,
      anon_sym_foreach,
    ACTIONS(7), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(9), 1,
      anon_sym_0o,
    ACTIONS(11), 1,
      anon_sym_0x,
    ACTIONS(13), 1,
      anon_sym_SQUOTE,
    ACTIONS(15), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(19), 1,
      anon_sym_LBRACK,
    ACTIONS(21), 1,
      anon_sym_LBRACE,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(129), 1,
      anon_sym_endif,
    STATE(145), 1,
      sym_literal,
    ACTIONS(17), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(10), 2,
      sym_statement,
      aux_sym_build_definition_repeat1,
    STATE(119), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(134), 3,
      sym_selection_statement,
      sym_iteration_statement,
      sym_expression,
    STATE(136), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(144), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1095] = 15,
    ACTIONS(131), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(133), 1,
      anon_sym_0o,
    ACTIONS(135), 1,
      anon_sym_0x,
    ACTIONS(137), 1,
      anon_sym_SQUOTE,
    ACTIONS(139), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(143), 1,
      anon_sym_LBRACK,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(147), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      sym_literal,
    STATE(83), 1,
      sym_key_value_item,
    STATE(147), 1,
      sym_expression,
    ACTIONS(141), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1149] = 15,
    ACTIONS(131), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(133), 1,
      anon_sym_0o,
    ACTIONS(135), 1,
      anon_sym_0x,
    ACTIONS(137), 1,
      anon_sym_SQUOTE,
    ACTIONS(139), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(143), 1,
      anon_sym_LBRACK,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(149), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      sym_literal,
    STATE(87), 1,
      sym_key_value_item,
    STATE(147), 1,
      sym_expression,
    ACTIONS(141), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1203] = 15,
    ACTIONS(131), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(133), 1,
      anon_sym_0o,
    ACTIONS(135), 1,
      anon_sym_0x,
    ACTIONS(137), 1,
      anon_sym_SQUOTE,
    ACTIONS(139), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(143), 1,
      anon_sym_LBRACK,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(151), 1,
      anon_sym_RBRACE,
    STATE(44), 1,
      sym_literal,
    STATE(79), 1,
      sym_key_value_item,
    STATE(147), 1,
      sym_expression,
    ACTIONS(141), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1257] = 14,
    ACTIONS(131), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(133), 1,
      anon_sym_0o,
    ACTIONS(135), 1,
      anon_sym_0x,
    ACTIONS(137), 1,
      anon_sym_SQUOTE,
    ACTIONS(139), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(143), 1,
      anon_sym_LBRACK,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(153), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      sym_literal,
    STATE(86), 1,
      sym_expression,
    ACTIONS(141), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1308] = 14,
    ACTIONS(155), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(157), 1,
      anon_sym_0o,
    ACTIONS(159), 1,
      anon_sym_0x,
    ACTIONS(161), 1,
      anon_sym_SQUOTE,
    ACTIONS(163), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(167), 1,
      anon_sym_LBRACK,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    STATE(74), 1,
      sym_condition,
    STATE(91), 1,
      sym_literal,
    STATE(111), 1,
      sym_expression,
    ACTIONS(165), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(94), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(93), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(92), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1359] = 14,
    ACTIONS(131), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(133), 1,
      anon_sym_0o,
    ACTIONS(135), 1,
      anon_sym_0x,
    ACTIONS(137), 1,
      anon_sym_SQUOTE,
    ACTIONS(139), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(143), 1,
      anon_sym_LBRACK,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(171), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      sym_literal,
    STATE(78), 1,
      sym_expression,
    ACTIONS(141), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1410] = 14,
    ACTIONS(131), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(133), 1,
      anon_sym_0o,
    ACTIONS(135), 1,
      anon_sym_0x,
    ACTIONS(137), 1,
      anon_sym_SQUOTE,
    ACTIONS(139), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(143), 1,
      anon_sym_LBRACK,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    ACTIONS(173), 1,
      anon_sym_RBRACK,
    STATE(44), 1,
      sym_literal,
    STATE(85), 1,
      sym_expression,
    ACTIONS(141), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1461] = 14,
    ACTIONS(131), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(133), 1,
      anon_sym_0o,
    ACTIONS(135), 1,
      anon_sym_0x,
    ACTIONS(137), 1,
      anon_sym_SQUOTE,
    ACTIONS(139), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(143), 1,
      anon_sym_LBRACK,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_literal,
    STATE(113), 1,
      sym_key_value_item,
    STATE(147), 1,
      sym_expression,
    ACTIONS(141), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1512] = 14,
    ACTIONS(155), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(157), 1,
      anon_sym_0o,
    ACTIONS(159), 1,
      anon_sym_0x,
    ACTIONS(161), 1,
      anon_sym_SQUOTE,
    ACTIONS(163), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(167), 1,
      anon_sym_LBRACK,
    ACTIONS(169), 1,
      anon_sym_LBRACE,
    STATE(72), 1,
      sym_condition,
    STATE(91), 1,
      sym_literal,
    STATE(111), 1,
      sym_expression,
    ACTIONS(165), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(94), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(93), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(92), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1563] = 13,
    ACTIONS(131), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(133), 1,
      anon_sym_0o,
    ACTIONS(135), 1,
      anon_sym_0x,
    ACTIONS(137), 1,
      anon_sym_SQUOTE,
    ACTIONS(139), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(143), 1,
      anon_sym_LBRACK,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_literal,
    STATE(89), 1,
      sym_expression,
    ACTIONS(141), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1611] = 13,
    ACTIONS(131), 1,
      sym__DECIMAL_NUMBER,
    ACTIONS(133), 1,
      anon_sym_0o,
    ACTIONS(135), 1,
      anon_sym_0x,
    ACTIONS(137), 1,
      anon_sym_SQUOTE,
    ACTIONS(139), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(143), 1,
      anon_sym_LBRACK,
    ACTIONS(145), 1,
      anon_sym_LBRACE,
    STATE(44), 1,
      sym_literal,
    STATE(112), 1,
      sym_expression,
    ACTIONS(141), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(49), 2,
      sym_string_simple,
      sym_string_multiline,
    STATE(46), 3,
      sym_decimal_literal,
      sym_octal_literal,
      sym_hex_literal,
    STATE(45), 5,
      sym_integer_literal,
      sym_string_literal,
      sym_boolean_literal,
      sym_array_literal,
      sym_dictionary_literal,
  [1659] = 2,
    ACTIONS(177), 2,
      sym__DECIMAL_NUMBER,
      anon_sym_SQUOTE,
    ACTIONS(175), 16,
      anon_sym_if,
      anon_sym_elif,
      anon_sym_else,
      anon_sym_endif,
      anon_sym_foreach,
      anon_sym_endforeach,
      anon_sym_break,
      anon_sym_continue,
      anon_sym_0o,
      anon_sym_0x,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_comment,
  [1682] = 2,
    ACTIONS(181), 2,
      sym__DECIMAL_NUMBER,
      anon_sym_SQUOTE,
    ACTIONS(179), 13,
      anon_sym_if,
      anon_sym_foreach,
      anon_sym_endforeach,
      anon_sym_break,
      anon_sym_continue,
      anon_sym_0o,
      anon_sym_0x,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_comment,
  [1702] = 2,
    ACTIONS(177), 2,
      sym__DECIMAL_NUMBER,
      anon_sym_SQUOTE,
    ACTIONS(175), 11,
      ts_builtin_sym_end,
      anon_sym_if,
      anon_sym_foreach,
      anon_sym_0o,
      anon_sym_0x,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
      anon_sym_true,
      anon_sym_false,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      sym_comment,
  [1720] = 4,
    ACTIONS(185), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(187), 1,
      aux_sym_string_multiline_token1,
    STATE(34), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(183), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1735] = 4,
    ACTIONS(187), 1,
      aux_sym_string_multiline_token1,
    ACTIONS(189), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    STATE(34), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(183), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1750] = 4,
    ACTIONS(194), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(196), 1,
      aux_sym_string_multiline_token1,
    STATE(34), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(191), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1765] = 4,
    ACTIONS(201), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(203), 1,
      aux_sym_string_multiline_token1,
    STATE(37), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(199), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1780] = 4,
    ACTIONS(207), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(209), 1,
      aux_sym_string_multiline_token1,
    STATE(33), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(205), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1795] = 4,
    ACTIONS(187), 1,
      aux_sym_string_multiline_token1,
    ACTIONS(211), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    STATE(34), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(183), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1810] = 4,
    ACTIONS(215), 1,
      anon_sym_SQUOTE_SQUOTE_SQUOTE,
    ACTIONS(217), 1,
      aux_sym_string_multiline_token1,
    STATE(32), 1,
      aux_sym_string_multiline_repeat1,
    ACTIONS(213), 3,
      sym_escape_sequence,
      anon_sym_SQUOTE,
      anon_sym_SQUOTE_SQUOTE,
  [1825] = 1,
    ACTIONS(219), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1832] = 1,
    ACTIONS(221), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1839] = 1,
    ACTIONS(223), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1846] = 1,
    ACTIONS(225), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1853] = 4,
    ACTIONS(227), 1,
      sym_escape_sequence,
    ACTIONS(229), 1,
      anon_sym_SQUOTE,
    ACTIONS(231), 1,
      aux_sym_string_simple_token1,
    STATE(54), 1,
      aux_sym_string_simple_repeat1,
  [1866] = 1,
    ACTIONS(233), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1873] = 1,
    ACTIONS(235), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1880] = 1,
    ACTIONS(237), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1887] = 4,
    ACTIONS(227), 1,
      sym_escape_sequence,
    ACTIONS(231), 1,
      aux_sym_string_simple_token1,
    ACTIONS(239), 1,
      anon_sym_SQUOTE,
    STATE(54), 1,
      aux_sym_string_simple_repeat1,
  [1900] = 4,
    ACTIONS(241), 1,
      sym_escape_sequence,
    ACTIONS(243), 1,
      anon_sym_SQUOTE,
    ACTIONS(245), 1,
      aux_sym_string_simple_token1,
    STATE(47), 1,
      aux_sym_string_simple_repeat1,
  [1913] = 1,
    ACTIONS(247), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1920] = 1,
    ACTIONS(249), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1927] = 1,
    ACTIONS(251), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1934] = 1,
    ACTIONS(253), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1941] = 4,
    ACTIONS(255), 1,
      sym_escape_sequence,
    ACTIONS(257), 1,
      anon_sym_SQUOTE,
    ACTIONS(259), 1,
      aux_sym_string_simple_token1,
    STATE(43), 1,
      aux_sym_string_simple_repeat1,
  [1954] = 4,
    ACTIONS(261), 1,
      sym_escape_sequence,
    ACTIONS(264), 1,
      anon_sym_SQUOTE,
    ACTIONS(266), 1,
      aux_sym_string_simple_token1,
    STATE(54), 1,
      aux_sym_string_simple_repeat1,
  [1967] = 1,
    ACTIONS(269), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1974] = 4,
    ACTIONS(227), 1,
      sym_escape_sequence,
    ACTIONS(231), 1,
      aux_sym_string_simple_token1,
    ACTIONS(271), 1,
      anon_sym_SQUOTE,
    STATE(54), 1,
      aux_sym_string_simple_repeat1,
  [1987] = 1,
    ACTIONS(273), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [1994] = 3,
    ACTIONS(275), 1,
      anon_sym_elif,
    STATE(58), 1,
      aux_sym_selection_statement_repeat1,
    ACTIONS(278), 2,
      anon_sym_else,
      anon_sym_endif,
  [2005] = 4,
    ACTIONS(25), 1,
      anon_sym_elif,
    ACTIONS(129), 1,
      anon_sym_endif,
    ACTIONS(280), 1,
      anon_sym_else,
    STATE(58), 1,
      aux_sym_selection_statement_repeat1,
  [2018] = 1,
    ACTIONS(282), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [2025] = 4,
    ACTIONS(25), 1,
      anon_sym_elif,
    ACTIONS(77), 1,
      anon_sym_else,
    ACTIONS(79), 1,
      anon_sym_endif,
    STATE(58), 1,
      aux_sym_selection_statement_repeat1,
  [2038] = 1,
    ACTIONS(284), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [2045] = 4,
    ACTIONS(286), 1,
      sym_escape_sequence,
    ACTIONS(288), 1,
      anon_sym_SQUOTE,
    ACTIONS(290), 1,
      aux_sym_string_simple_token1,
    STATE(56), 1,
      aux_sym_string_simple_repeat1,
  [2058] = 1,
    ACTIONS(292), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [2065] = 1,
    ACTIONS(294), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [2072] = 1,
    ACTIONS(296), 4,
      anon_sym_COLON,
      anon_sym_COMMA,
      anon_sym_RBRACK,
      anon_sym_RBRACE,
  [2079] = 3,
    ACTIONS(298), 1,
      anon_sym_COLON,
    ACTIONS(300), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym_identifier_list_repeat1,
  [2089] = 3,
    ACTIONS(302), 1,
      anon_sym_COMMA,
    ACTIONS(305), 1,
      anon_sym_RBRACK,
    STATE(68), 1,
      aux_sym_array_literal_repeat1,
  [2099] = 3,
    ACTIONS(307), 1,
      anon_sym_COMMA,
    ACTIONS(309), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      aux_sym_dictionary_literal_repeat1,
  [2109] = 3,
    ACTIONS(311), 1,
      anon_sym_COLON,
    ACTIONS(313), 1,
      anon_sym_COMMA,
    STATE(70), 1,
      aux_sym_identifier_list_repeat1,
  [2119] = 3,
    ACTIONS(316), 1,
      anon_sym_COMMA,
    ACTIONS(319), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      aux_sym_dictionary_literal_repeat1,
  [2129] = 2,
    STATE(9), 1,
      sym__NEWLINE,
    ACTIONS(321), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2137] = 2,
    STATE(5), 1,
      sym__NEWLINE,
    ACTIONS(323), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2145] = 2,
    STATE(2), 1,
      sym__NEWLINE,
    ACTIONS(325), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2153] = 3,
    ACTIONS(307), 1,
      anon_sym_COMMA,
    ACTIONS(327), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      aux_sym_dictionary_literal_repeat1,
  [2163] = 2,
    STATE(30), 1,
      sym__NEWLINE,
    ACTIONS(329), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2171] = 3,
    ACTIONS(331), 1,
      anon_sym_COMMA,
    ACTIONS(333), 1,
      anon_sym_RBRACK,
    STATE(68), 1,
      aux_sym_array_literal_repeat1,
  [2181] = 3,
    ACTIONS(331), 1,
      anon_sym_COMMA,
    ACTIONS(335), 1,
      anon_sym_RBRACK,
    STATE(81), 1,
      aux_sym_array_literal_repeat1,
  [2191] = 3,
    ACTIONS(307), 1,
      anon_sym_COMMA,
    ACTIONS(337), 1,
      anon_sym_RBRACE,
    STATE(82), 1,
      aux_sym_dictionary_literal_repeat1,
  [2201] = 3,
    ACTIONS(339), 1,
      sym__IDENTIFIER,
    STATE(84), 1,
      sym_id_expression,
    STATE(125), 1,
      sym_identifier_list,
  [2211] = 3,
    ACTIONS(331), 1,
      anon_sym_COMMA,
    ACTIONS(341), 1,
      anon_sym_RBRACK,
    STATE(68), 1,
      aux_sym_array_literal_repeat1,
  [2221] = 3,
    ACTIONS(307), 1,
      anon_sym_COMMA,
    ACTIONS(343), 1,
      anon_sym_RBRACE,
    STATE(71), 1,
      aux_sym_dictionary_literal_repeat1,
  [2231] = 3,
    ACTIONS(307), 1,
      anon_sym_COMMA,
    ACTIONS(345), 1,
      anon_sym_RBRACE,
    STATE(75), 1,
      aux_sym_dictionary_literal_repeat1,
  [2241] = 3,
    ACTIONS(300), 1,
      anon_sym_COMMA,
    ACTIONS(347), 1,
      anon_sym_COLON,
    STATE(67), 1,
      aux_sym_identifier_list_repeat1,
  [2251] = 3,
    ACTIONS(331), 1,
      anon_sym_COMMA,
    ACTIONS(349), 1,
      anon_sym_RBRACK,
    STATE(77), 1,
      aux_sym_array_literal_repeat1,
  [2261] = 3,
    ACTIONS(331), 1,
      anon_sym_COMMA,
    ACTIONS(351), 1,
      anon_sym_RBRACK,
    STATE(88), 1,
      aux_sym_array_literal_repeat1,
  [2271] = 3,
    ACTIONS(307), 1,
      anon_sym_COMMA,
    ACTIONS(353), 1,
      anon_sym_RBRACE,
    STATE(69), 1,
      aux_sym_dictionary_literal_repeat1,
  [2281] = 3,
    ACTIONS(331), 1,
      anon_sym_COMMA,
    ACTIONS(355), 1,
      anon_sym_RBRACK,
    STATE(68), 1,
      aux_sym_array_literal_repeat1,
  [2291] = 1,
    ACTIONS(357), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2296] = 1,
    ACTIONS(359), 2,
      anon_sym_COLON,
      anon_sym_COMMA,
  [2301] = 1,
    ACTIONS(361), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2306] = 1,
    ACTIONS(363), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2311] = 1,
    ACTIONS(365), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2316] = 1,
    ACTIONS(367), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2321] = 2,
    ACTIONS(369), 1,
      sym__IDENTIFIER,
    STATE(73), 1,
      sym_id_expression,
  [2328] = 1,
    ACTIONS(371), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2333] = 1,
    ACTIONS(373), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2338] = 1,
    ACTIONS(375), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2343] = 1,
    ACTIONS(377), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2348] = 1,
    ACTIONS(379), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2353] = 1,
    ACTIONS(381), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2358] = 2,
    ACTIONS(339), 1,
      sym__IDENTIFIER,
    STATE(103), 1,
      sym_id_expression,
  [2365] = 1,
    ACTIONS(311), 2,
      anon_sym_COLON,
      anon_sym_COMMA,
  [2370] = 1,
    ACTIONS(383), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2375] = 1,
    ACTIONS(385), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2380] = 1,
    ACTIONS(387), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2385] = 1,
    ACTIONS(389), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2390] = 1,
    ACTIONS(391), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2395] = 1,
    ACTIONS(393), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2400] = 1,
    ACTIONS(395), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2405] = 1,
    ACTIONS(397), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2410] = 1,
    ACTIONS(305), 2,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [2415] = 1,
    ACTIONS(319), 2,
      anon_sym_COMMA,
      anon_sym_RBRACE,
  [2420] = 1,
    ACTIONS(399), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2425] = 1,
    ACTIONS(401), 2,
      anon_sym_LF2,
      anon_sym_CR_LF,
  [2430] = 1,
    ACTIONS(403), 1,
      anon_sym_LF,
  [2434] = 1,
    ACTIONS(253), 1,
      anon_sym_LF,
  [2438] = 1,
    ACTIONS(405), 1,
      anon_sym_LF,
  [2442] = 1,
    ACTIONS(247), 1,
      anon_sym_LF,
  [2446] = 1,
    ACTIONS(407), 1,
      sym__HEX_NUMBER,
  [2450] = 1,
    ACTIONS(409), 1,
      anon_sym_LF,
  [2454] = 1,
    ACTIONS(225), 1,
      anon_sym_LF,
  [2458] = 1,
    ACTIONS(411), 1,
      anon_sym_LF,
  [2462] = 1,
    ACTIONS(294), 1,
      anon_sym_LF,
  [2466] = 1,
    ACTIONS(413), 1,
      anon_sym_COLON,
  [2470] = 1,
    ACTIONS(219), 1,
      anon_sym_LF,
  [2474] = 1,
    ACTIONS(296), 1,
      anon_sym_LF,
  [2478] = 1,
    ACTIONS(415), 1,
      sym__OCTAL_NUMBER,
  [2482] = 1,
    ACTIONS(417), 1,
      sym__HEX_NUMBER,
  [2486] = 1,
    ACTIONS(419), 1,
      anon_sym_LF,
  [2490] = 1,
    ACTIONS(223), 1,
      anon_sym_LF,
  [2494] = 1,
    ACTIONS(421), 1,
      anon_sym_LF,
  [2498] = 1,
    ACTIONS(423), 1,
      anon_sym_LF,
  [2502] = 1,
    ACTIONS(425), 1,
      anon_sym_LF,
  [2506] = 1,
    ACTIONS(427), 1,
      anon_sym_LF,
  [2510] = 1,
    ACTIONS(237), 1,
      anon_sym_LF,
  [2514] = 1,
    ACTIONS(292), 1,
      anon_sym_LF,
  [2518] = 1,
    ACTIONS(284), 1,
      anon_sym_LF,
  [2522] = 1,
    ACTIONS(282), 1,
      anon_sym_LF,
  [2526] = 1,
    ACTIONS(249), 1,
      anon_sym_LF,
  [2530] = 1,
    ACTIONS(429), 1,
      sym__OCTAL_NUMBER,
  [2534] = 1,
    ACTIONS(431), 1,
      sym__HEX_NUMBER,
  [2538] = 1,
    ACTIONS(433), 1,
      sym__OCTAL_NUMBER,
  [2542] = 1,
    ACTIONS(235), 1,
      anon_sym_LF,
  [2546] = 1,
    ACTIONS(233), 1,
      anon_sym_LF,
  [2550] = 1,
    ACTIONS(435), 1,
      ts_builtin_sym_end,
  [2554] = 1,
    ACTIONS(437), 1,
      anon_sym_COLON,
  [2558] = 1,
    ACTIONS(439), 1,
      ts_builtin_sym_end,
  [2562] = 1,
    ACTIONS(273), 1,
      anon_sym_LF,
  [2566] = 1,
    ACTIONS(269), 1,
      anon_sym_LF,
  [2570] = 1,
    ACTIONS(221), 1,
      anon_sym_LF,
  [2574] = 1,
    ACTIONS(251), 1,
      anon_sym_LF,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 75,
  [SMALL_STATE(4)] = 146,
  [SMALL_STATE(5)] = 217,
  [SMALL_STATE(6)] = 288,
  [SMALL_STATE(7)] = 363,
  [SMALL_STATE(8)] = 431,
  [SMALL_STATE(9)] = 499,
  [SMALL_STATE(10)] = 567,
  [SMALL_STATE(11)] = 633,
  [SMALL_STATE(12)] = 699,
  [SMALL_STATE(13)] = 765,
  [SMALL_STATE(14)] = 831,
  [SMALL_STATE(15)] = 897,
  [SMALL_STATE(16)] = 963,
  [SMALL_STATE(17)] = 1029,
  [SMALL_STATE(18)] = 1095,
  [SMALL_STATE(19)] = 1149,
  [SMALL_STATE(20)] = 1203,
  [SMALL_STATE(21)] = 1257,
  [SMALL_STATE(22)] = 1308,
  [SMALL_STATE(23)] = 1359,
  [SMALL_STATE(24)] = 1410,
  [SMALL_STATE(25)] = 1461,
  [SMALL_STATE(26)] = 1512,
  [SMALL_STATE(27)] = 1563,
  [SMALL_STATE(28)] = 1611,
  [SMALL_STATE(29)] = 1659,
  [SMALL_STATE(30)] = 1682,
  [SMALL_STATE(31)] = 1702,
  [SMALL_STATE(32)] = 1720,
  [SMALL_STATE(33)] = 1735,
  [SMALL_STATE(34)] = 1750,
  [SMALL_STATE(35)] = 1765,
  [SMALL_STATE(36)] = 1780,
  [SMALL_STATE(37)] = 1795,
  [SMALL_STATE(38)] = 1810,
  [SMALL_STATE(39)] = 1825,
  [SMALL_STATE(40)] = 1832,
  [SMALL_STATE(41)] = 1839,
  [SMALL_STATE(42)] = 1846,
  [SMALL_STATE(43)] = 1853,
  [SMALL_STATE(44)] = 1866,
  [SMALL_STATE(45)] = 1873,
  [SMALL_STATE(46)] = 1880,
  [SMALL_STATE(47)] = 1887,
  [SMALL_STATE(48)] = 1900,
  [SMALL_STATE(49)] = 1913,
  [SMALL_STATE(50)] = 1920,
  [SMALL_STATE(51)] = 1927,
  [SMALL_STATE(52)] = 1934,
  [SMALL_STATE(53)] = 1941,
  [SMALL_STATE(54)] = 1954,
  [SMALL_STATE(55)] = 1967,
  [SMALL_STATE(56)] = 1974,
  [SMALL_STATE(57)] = 1987,
  [SMALL_STATE(58)] = 1994,
  [SMALL_STATE(59)] = 2005,
  [SMALL_STATE(60)] = 2018,
  [SMALL_STATE(61)] = 2025,
  [SMALL_STATE(62)] = 2038,
  [SMALL_STATE(63)] = 2045,
  [SMALL_STATE(64)] = 2058,
  [SMALL_STATE(65)] = 2065,
  [SMALL_STATE(66)] = 2072,
  [SMALL_STATE(67)] = 2079,
  [SMALL_STATE(68)] = 2089,
  [SMALL_STATE(69)] = 2099,
  [SMALL_STATE(70)] = 2109,
  [SMALL_STATE(71)] = 2119,
  [SMALL_STATE(72)] = 2129,
  [SMALL_STATE(73)] = 2137,
  [SMALL_STATE(74)] = 2145,
  [SMALL_STATE(75)] = 2153,
  [SMALL_STATE(76)] = 2163,
  [SMALL_STATE(77)] = 2171,
  [SMALL_STATE(78)] = 2181,
  [SMALL_STATE(79)] = 2191,
  [SMALL_STATE(80)] = 2201,
  [SMALL_STATE(81)] = 2211,
  [SMALL_STATE(82)] = 2221,
  [SMALL_STATE(83)] = 2231,
  [SMALL_STATE(84)] = 2241,
  [SMALL_STATE(85)] = 2251,
  [SMALL_STATE(86)] = 2261,
  [SMALL_STATE(87)] = 2271,
  [SMALL_STATE(88)] = 2281,
  [SMALL_STATE(89)] = 2291,
  [SMALL_STATE(90)] = 2296,
  [SMALL_STATE(91)] = 2301,
  [SMALL_STATE(92)] = 2306,
  [SMALL_STATE(93)] = 2311,
  [SMALL_STATE(94)] = 2316,
  [SMALL_STATE(95)] = 2321,
  [SMALL_STATE(96)] = 2328,
  [SMALL_STATE(97)] = 2333,
  [SMALL_STATE(98)] = 2338,
  [SMALL_STATE(99)] = 2343,
  [SMALL_STATE(100)] = 2348,
  [SMALL_STATE(101)] = 2353,
  [SMALL_STATE(102)] = 2358,
  [SMALL_STATE(103)] = 2365,
  [SMALL_STATE(104)] = 2370,
  [SMALL_STATE(105)] = 2375,
  [SMALL_STATE(106)] = 2380,
  [SMALL_STATE(107)] = 2385,
  [SMALL_STATE(108)] = 2390,
  [SMALL_STATE(109)] = 2395,
  [SMALL_STATE(110)] = 2400,
  [SMALL_STATE(111)] = 2405,
  [SMALL_STATE(112)] = 2410,
  [SMALL_STATE(113)] = 2415,
  [SMALL_STATE(114)] = 2420,
  [SMALL_STATE(115)] = 2425,
  [SMALL_STATE(116)] = 2430,
  [SMALL_STATE(117)] = 2434,
  [SMALL_STATE(118)] = 2438,
  [SMALL_STATE(119)] = 2442,
  [SMALL_STATE(120)] = 2446,
  [SMALL_STATE(121)] = 2450,
  [SMALL_STATE(122)] = 2454,
  [SMALL_STATE(123)] = 2458,
  [SMALL_STATE(124)] = 2462,
  [SMALL_STATE(125)] = 2466,
  [SMALL_STATE(126)] = 2470,
  [SMALL_STATE(127)] = 2474,
  [SMALL_STATE(128)] = 2478,
  [SMALL_STATE(129)] = 2482,
  [SMALL_STATE(130)] = 2486,
  [SMALL_STATE(131)] = 2490,
  [SMALL_STATE(132)] = 2494,
  [SMALL_STATE(133)] = 2498,
  [SMALL_STATE(134)] = 2502,
  [SMALL_STATE(135)] = 2506,
  [SMALL_STATE(136)] = 2510,
  [SMALL_STATE(137)] = 2514,
  [SMALL_STATE(138)] = 2518,
  [SMALL_STATE(139)] = 2522,
  [SMALL_STATE(140)] = 2526,
  [SMALL_STATE(141)] = 2530,
  [SMALL_STATE(142)] = 2534,
  [SMALL_STATE(143)] = 2538,
  [SMALL_STATE(144)] = 2542,
  [SMALL_STATE(145)] = 2546,
  [SMALL_STATE(146)] = 2550,
  [SMALL_STATE(147)] = 2554,
  [SMALL_STATE(148)] = 2558,
  [SMALL_STATE(149)] = 2562,
  [SMALL_STATE(150)] = 2566,
  [SMALL_STATE(151)] = 2570,
  [SMALL_STATE(152)] = 2574,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(131),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(22),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(80),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(76),
  [44] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(131),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(143),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(120),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(53),
  [56] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(36),
  [59] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(122),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(24),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(18),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_iteration_statement_repeat1, 2), SHIFT_REPEAT(134),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [81] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(22),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2),
  [86] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(80),
  [89] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(131),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(143),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(120),
  [98] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(53),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(36),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(122),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(24),
  [110] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(18),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(134),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selection_statement_repeat1, 4),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selection_statement_repeat1, 3),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_build_definition_repeat1, 2), SHIFT_REPEAT(118),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_build_definition, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(121),
  [131] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(149),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [155] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(150),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 2),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 2),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_jump_statement, 2),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_jump_statement, 2),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [185] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [189] = {.entry = {.count = 1, .reusable = false}}, SHIFT(138),
  [191] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_multiline_repeat1, 2), SHIFT_REPEAT(34),
  [194] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_multiline_repeat1, 2),
  [196] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_multiline_repeat1, 2), SHIFT_REPEAT(34),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [201] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [203] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [205] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(151),
  [209] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [211] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [213] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_octal_literal, 2),
  [221] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_multiline, 2),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decimal_literal, 1),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean_literal, 1),
  [227] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(139),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_integer_literal, 1),
  [239] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [241] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 1),
  [249] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hex_literal, 2),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_simple, 2),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary_literal, 3),
  [255] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [257] = {.entry = {.count = 1, .reusable = false}}, SHIFT(152),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [261] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_simple_repeat1, 2), SHIFT_REPEAT(54),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_simple_repeat1, 2),
  [266] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_simple_repeat1, 2), SHIFT_REPEAT(54),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 2),
  [271] = {.entry = {.count = 1, .reusable = false}}, SHIFT(104),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary_literal, 2),
  [275] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_selection_statement_repeat1, 2), SHIFT_REPEAT(26),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_selection_statement_repeat1, 2),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_simple, 3),
  [284] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_multiline, 3),
  [286] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [288] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [292] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 3),
  [294] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary_literal, 4),
  [296] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array_literal, 4),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_list, 2),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [302] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2), SHIFT_REPEAT(28),
  [305] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_literal_repeat1, 2),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [311] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_identifier_list_repeat1, 2),
  [313] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_identifier_list_repeat1, 2), SHIFT_REPEAT(102),
  [316] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dictionary_literal_repeat1, 2), SHIFT_REPEAT(25),
  [319] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dictionary_literal_repeat1, 2),
  [321] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [323] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [325] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [329] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [347] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_identifier_list, 1),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_key_value_item, 3, .production_id = 1),
  [359] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_id_expression, 1),
  [361] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [363] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal, 1),
  [365] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_integer_literal, 1),
  [367] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 1),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [371] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_octal_literal, 2),
  [373] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hex_literal, 2),
  [375] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_simple, 2),
  [377] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_multiline, 2),
  [379] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 2),
  [381] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary_literal, 2),
  [383] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_simple, 3),
  [385] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_multiline, 3),
  [387] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 3),
  [389] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary_literal, 3),
  [391] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array_literal, 4),
  [393] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary_literal, 4),
  [395] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decimal_literal, 1),
  [397] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_condition, 1),
  [399] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean_literal, 1),
  [401] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_id_expression, 1),
  [403] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_iteration_statement, 6),
  [405] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [407] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [409] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 6),
  [411] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 5),
  [413] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [415] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [417] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [419] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_iteration_statement, 7),
  [421] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 8),
  [423] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 4),
  [425] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [427] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_selection_statement, 7),
  [429] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [431] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [433] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [435] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [437] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [439] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_meson(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
